// Where each chapter starts in docs/media/walkthrough.mp4, in seconds.
//
// Generated by tools/capture/join.mjs when the chapters are joined --
// do not edit by hand. A browser will not surface an mp4's own chapter
// marks, so the Help dialog seeks with these instead.

export const film = [
	{ at: 0, title: "One — The Yard" },
	{ at: 107, title: "Two — To Get" },
	{ at: 203, title: "Three — Quests" },
	{ at: 264, title: "Four — Your Ship" },
	{ at: 409, title: "Five — The Map" },
	{ at: 566, title: "Six — A Run" },
	{ at: 731, title: "Seven — The Harbour" },
];
