// Where each chapter starts in docs/media/walkthrough.mp4, in seconds.
//
// Generated by tools/capture/join.mjs when the chapters are joined --
// do not edit by hand. A browser will not surface an mp4's own chapter
// marks, so the Help dialog seeks with these instead.

export const film = [
	{ at: 0, title: "One — The Yard" },
	{ at: 137, title: "Two — To Get" },
	{ at: 231, title: "Three — Quests" },
	{ at: 291, title: "Four — Your Ship" },
	{ at: 446, title: "Five — The Map" },
	{ at: 650, title: "Six — A Run" },
	{ at: 979, title: "Seven — The Harbour" },
];
