// Where each chapter starts in docs/media/walkthrough.mp4, in seconds.
//
// Generated by tools/capture/join.mjs when the chapters are joined --
// do not edit by hand. A browser will not surface an mp4's own chapter
// marks, so the Help dialog seeks with these instead.

export const film = [
	{ at: 0, title: "One — The Yard" },
	{ at: 221, title: "Two — The Workshop" },
	{ at: 374, title: "Three — To Get" },
	{ at: 540, title: "Four — Quests" },
	{ at: 673, title: "Five — Your Ship" },
	{ at: 877, title: "Six — The Map" },
	{ at: 1075, title: "Seven — Routes and Drawings" },
	{ at: 1227, title: "Eight — Today’s Board" },
	{ at: 1510, title: "Nine — A Silver Day" },
	{ at: 1777, title: "Ten — At the Wharf" },
	{ at: 1953, title: "Eleven — Under Sail" },
	{ at: 2133, title: "Twelve — A Stock Day" },
	{ at: 2243, title: "Thirteen — A Crow Coin Day" },
	{ at: 2334, title: "Fourteen — A Material Day" },
	{ at: 2479, title: "Fifteen — A Short Trip" },
	{ at: 2577, title: "Sixteen — The Character Bag" },
	{ at: 2683, title: "Seventeen — The Harbour" },
];
