// The icon BDOCodex draws beside each quest, by its codex id.
//
// Generated by tools/fetch-quest-icons.mjs -- do not edit by hand.
// The files are under icons/quest/. Far fewer files than quests: the
// codex names them after the errand, so a row of quests reads as a set
// -- every Ravinia letter one picture, every Old Moon Guild hunt
// another. A quest with no entry here has none on the codex.
//
// Read 2026-09-15.

export const QUEST_ICONS = {
	'3709/7': 'rabinia.webp',
	'3711/2': 'rabinia.webp',
	'3712/1': 'rabinia.webp',
	'3707/23': 'greatseasub3.webp',
	'3707/9': 'greatseasub3.webp',
	'3707/10': 'greatseasub2.webp',
	'3707/11': 'greatseasub4.webp',
	'3707/19': 'greatseasub3.webp',
	'3707/20': 'greatseasub2.webp',
	'3707/21': 'greatseasub4.webp',
	'3707/6': 'seashipevent_005.webp',
	'3707/7': 'greatsea_04.webp',
	'3707/8': 'greatsea_08.webp',
	'3707/22': 'seashipevent_005.webp',
	'3707/24': 'fishingrod.webp',
	'3707/25': 'greatseasub1.webp',
	'3740/1': 'greatesea_19.webp',
	'3740/2': 'greatesea_09.webp',
	'3726/1': 'greatseasub2.webp',
	'3726/2': 'greatseasub2.webp',
	'3839/1': 'greatsea_13.webp',
	'3704/10': 'greatesea_004.webp',
	'3704/11': 'greatesea_005.webp',
	'3704/13': 'greatesea_007.webp',
	'3704/7': 'greatesea_001.webp',
	'3704/8': 'greatesea_002.webp',
	'3704/9': 'greatesea_003.webp',
	'3736/1': 'newsea_001.webp',
	'3727/1': 'robinia.webp',
	'3727/2': 'robinia.webp',
	'3736/12': 'newsea_001.webp',
	'3736/9': 'newsea_001.webp',
	'3736/10': '00043797.webp',
	'3736/11': '00043797.webp',
	'3720/1': 'greatesea_012.webp',
	'3707/26': 'ocean_new_monster_01.webp'
};

/** The icon for a quest, as a path the page can use, or '' if it has none. */
export const questIcon = q => (q && QUEST_ICONS[q.codex] ? `icons/quest/${QUEST_ICONS[q.codex]}` : '');
