// A recipe dictionary

export const recipes = {
	// Ships
	"Epheria Sailboat": {
		"Bartali Sailboat": 1,
		"Ship Upgrade Permit: Epheria Sailboat": 1,
		"+10 Bartali Sailboat: Old Figurehead": 1,
		"+10 Bartali Sailboat: Old Plating": 1,
		"+10 Bartali Sailboat: Old Cannon": 1,
		"+10 Bartali Sailboat: Old Wind Sail": 1,
		"Standardized Timber Square": 350,
		"Steel": 250,
		"Pine Plywood": 700,
		"Flax Fabric": 100,
		"Gold Bar 1,000G": 5
	},
	"Improved Epheria Sailboat": {
		"Epheria Sailboat": 1,
		"Bartali Sailboat: Old Figurehead": 1,
		"Bartali Sailboat: Old Plating": 1,
		"Bartali Sailboat: Old Cannon": 1,
		"Bartali Sailboat: Old Wind Sail": 1,
		"Standardized Timber Square": 250,
		"Steel": 200,
		"Pine Plywood": 500,
		"Flax Fabric": 100,
		"Hard Pillar": 30,
		"Ultimate Armor Reform Stone": 10
	},
	"Epheria Caravel": {
		"Epheria Sailboat": 1,
		"Ship Upgrade Permit: Epheria Caravel": 1,
		"+10 Epheria: Old Figurehead": 1,
		"+10 Epheria: Old Plating": 1,
		"+10 Epheria: Old Cannon": 1,
		"+10 Epheria: Old Wind Sail": 1,
		"Graphite Ingot for Upgrade": 100,
		"Timber for Upgrade": 100,
		"Adhesive for Upgrade": 100,
		"Island Tree Coated Plywood": 100,
		"Rock Salt Ingot": 100,
		"Deep Sea Memory Filled Glue": 4,
		"Seaweed Stalk": 4
	},
	"Carrack (Advance)": {
		"Epheria Caravel": 1,
		"+10 Epheria Caravel: Black Dragon Figurehead": 1,
		"+10 Epheria Caravel: Upgraded Plating": 1,
		"+10 Epheria Caravel: Mayna Cannon": 1,
		"+10 Epheria Caravel: Stratus Wind Sail": 1,
		"Moon Vein Flax Fabric": 180,
		"Deep Tide-Dyed Standardized Timber Square": 144,
		"Brilliant Rock Salt Ingot": 35,
		"Tear of the Ocean": 42,
		"Brilliant Pearl Shard": 35
	},
	"Carrack (Balance)": {
		"Epheria Caravel": 1,
		"+10 Epheria Caravel: Black Dragon Figurehead": 1,
		"+10 Epheria Caravel: Upgraded Plating": 1,
		"+10 Epheria Caravel: Mayna Cannon": 1,
		"+10 Epheria Caravel: Stratus Wind Sail": 1,
		"Moon Vein Flax Fabric": 180,
		"Deep Tide-Dyed Standardized Timber Square": 144,
		"Brilliant Rock Salt Ingot": 30,
		"Tear of the Ocean": 50,
		"Brilliant Pearl Shard": 30
	},
	"Epheria Frigate": {
		"Bartali Sailboat": 1,
		"Ship Upgrade Permit: Epheria Frigate": 1,
		"+10 Bartali Sailboat: Old Figurehead": 1,
		"+10 Bartali Sailboat: Old Plating": 1,
		"+10 Bartali Sailboat: Old Cannon": 1,
		"+10 Bartali Sailboat: Old Wind Sail": 1,
		"Standardized Timber Square": 450,
		"Jade Coral Ingot": 350,
		"Pine Coated Plywood": 750,
		"Enhanced Flax Fabric": 200,
		"Gold Bar 1,000G": 5
	},
	"Improved Epheria Frigate": {
		"Epheria Frigate": 1,
		"Bartali Sailboat: Old Figurehead": 1,
		"Bartali Sailboat: Old Plating": 1,
		"Bartali Sailboat: Old Cannon": 1,
		"Bartali Sailboat: Old Wind Sail": 1,
		"Standardized Timber Square": 250,
		"Steel": 200,
		"Pine Plywood": 500,
		"Flax Fabric": 100,
		"Hard Pillar": 30,
		"Ultimate Weapon Reform Stone": 10
	},
	"Epheria Galleass": {
		"Epheria Frigate": 1,
		"Ship Upgrade Permit: Epheria Galleass": 1,
		"+10 Epheria: Old Figurehead": 1,
		"+10 Epheria: Old Plating": 1,
		"+10 Epheria: Old Cannon": 1,
		"+10 Epheria: Old Wind Sail": 1,
		"Graphite Ingot for Upgrade": 100,
		"Timber for Upgrade": 100,
		"Adhesive for Upgrade": 100,
		"Island Tree Coated Plywood": 100,
		"Tide-Dyed Standardized Timber Square": 3,
		"Cobalt Ingot": 2,
		"Moon Scale Plywood": 10
	},
	"Carrack (Volante)": {
		"Epheria Galleass": 1,
		"+10 Epheria Galleass: Black Dragon Figurehead": 1,
		"+10 Epheria Galleass: Upgraded Plating": 1,
		"+10 Epheria Galleass: Mayna Cannon": 1,
		"+10 Epheria Galleass: Stratus Wind Sail": 1,
		"Moon Vein Flax Fabric": 210,
		"Deep Tide-Dyed Standardized Timber Square": 144,
		"Brilliant Rock Salt Ingot": 30,
		"Tear of the Ocean": 42,
		"Brilliant Pearl Shard": 30
	},
	"Carrack (Valor)": {
		"Epheria Galleass": 1,
		"+10 Epheria Galleass: Black Dragon Figurehead": 1,
		"+10 Epheria Galleass: Upgraded Plating": 1,
		"+10 Epheria Galleass: Mayna Cannon": 1,
		"+10 Epheria Galleass: Stratus Wind Sail": 1,
		"Moon Vein Flax Fabric": 180,
		"Deep Tide-Dyed Standardized Timber Square": 170,
		"Brilliant Rock Salt Ingot": 30,
		"Tear of the Ocean": 42,
		"Brilliant Pearl Shard": 30
	},

	"Panokseon": {
		"Blueprint: Panokseon": 30,
		"Wooden Nail Soaked in Seawater": 250,
		"Finely Polished Pine Plywood": 300,
		"Glue With Traces of Deep Waves": 200,
	},

	// Upgrade parts
	"Finely Polished Pine Plywood": {"Sangpyeong Coin": 10},
	"Graphite Ingot for Upgrade": {"Zinc Ingot": 100, "Sea Monster's Ooze": 1},
	"Timber for Upgrade": {"Old Tree Bark": 100, "Red Tree Lump": 100, "Sea Monster's Ooze": 1},
	"Adhesive for Upgrade": {"White Cedar Sap": 100, "Acacia Sap": 100, "Elder Tree Sap": 100, "Sea Monster's Ooze": 1},

	"Epheria Caravel: Black Dragon Figurehead": {
		"+10 Epheria Caravel: Brass Figurehead": 1,
		"Ruddy Manganese Nodule": 50,
		"Enhanced Island Tree Coated Plywood": 300,
		"Seaweed Stalk": 125,
		"Great Ocean Dark Iron": 150
	},
	"Epheria Caravel: Upgraded Plating": {
		"+10 Epheria Caravel: Enhanced Plating": 1,
		"Pure Pearl Crystal": 45,
		"Cox Pirates' Artifact (Parley Beginner)": 60,
		"Cox Pirates' Artifact (Combat)": 60,
		"Moon Scale Plywood": 200
	},
	"Epheria Caravel: Mayna Cannon": {
		"+10 Epheria Caravel: Verisha Cannon": 1,
		"Tide-Dyed Standardized Timber Square": 180,
		"Cox Pirates' Artifact (Combat)": 60,
		"Moon Scale Plywood": 200,
		"Bright Reef Piece": 180
	},
	"Epheria Caravel: Stratus Wind Sail": {
		"+10 Epheria Caravel: White Wind Sail": 1,
		"Ruddy Manganese Nodule": 40,
		"Cox Pirates' Artifact (Parley Expert)": 30,
		"Seaweed Stalk": 80,
		"Luminous Cobalt Ingot": 30
	},

	"Epheria Galleass: Black Dragon Figurehead": {
		"+10 Epheria Galleass: White Horn Figurehead": 1,
		"Ruddy Manganese Nodule": 50,
		"Enhanced Island Tree Coated Plywood": 300,
		"Seaweed Stalk": 125,
		"Great Ocean Dark Iron": 150
	},
	"Epheria Galleass: Upgraded Plating": {
		"+10 Epheria Galleass: Enhanced Plating": 1,
		"Pure Pearl Crystal": 45,
		"Cox Pirates' Artifact (Parley Beginner)": 60,
		"Cox Pirates' Artifact (Combat)": 125,
		"Moon Scale Plywood": 300
	},
	"Epheria Galleass: Mayna Cannon": {
		"+10 Epheria Galleass: Verisha Cannon": 1,
		"Tide-Dyed Standardized Timber Square": 180,
		"Cox Pirates' Artifact (Combat)": 125,
		"Moon Scale Plywood": 300,
		"Bright Reef Piece": 180
	},
	"Epheria Galleass: Stratus Wind Sail": {
		"+10 Epheria Galleass: White Wind Sail": 1,
		"Ruddy Manganese Nodule": 50,
		"Cox Pirates' Artifact (Parley Expert)": 30,
		"Seaweed Stalk": 125,
		"Luminous Cobalt Ingot": 30
	},

	// Gear (used for upgrading ship to next type)
	"+10 Bartali Sailboat: Old Figurehead": {"+9 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 10},
	"+9 Bartali Sailboat: Old Figurehead": {"+8 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 9},
	"+8 Bartali Sailboat: Old Figurehead": {"+7 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 8},
	"+7 Bartali Sailboat: Old Figurehead": {"+6 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 7},
	"+6 Bartali Sailboat: Old Figurehead": {"+5 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 6},
	"+5 Bartali Sailboat: Old Figurehead": {"+4 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 5},
	"+4 Bartali Sailboat: Old Figurehead": {"+3 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 4},
	"+3 Bartali Sailboat: Old Figurehead": {"+2 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 3},
	"+2 Bartali Sailboat: Old Figurehead": {"+1 Bartali Sailboat: Old Figurehead": 1, "Black Stone": 2},
	"+1 Bartali Sailboat: Old Figurehead": {"Bartali Sailboat: Old Figurehead": 1, "Black Stone": 1},
	"+10 Bartali Sailboat: Old Plating": {"+9 Bartali Sailboat: Old Plating": 1, "Black Stone": 10},
	"+9 Bartali Sailboat: Old Plating": {"+8 Bartali Sailboat: Old Plating": 1, "Black Stone": 9},
	"+8 Bartali Sailboat: Old Plating": {"+7 Bartali Sailboat: Old Plating": 1, "Black Stone": 8},
	"+7 Bartali Sailboat: Old Plating": {"+6 Bartali Sailboat: Old Plating": 1, "Black Stone": 7},
	"+6 Bartali Sailboat: Old Plating": {"+5 Bartali Sailboat: Old Plating": 1, "Black Stone": 6},
	"+5 Bartali Sailboat: Old Plating": {"+4 Bartali Sailboat: Old Plating": 1, "Black Stone": 5},
	"+4 Bartali Sailboat: Old Plating": {"+3 Bartali Sailboat: Old Plating": 1, "Black Stone": 4},
	"+3 Bartali Sailboat: Old Plating": {"+2 Bartali Sailboat: Old Plating": 1, "Black Stone": 3},
	"+2 Bartali Sailboat: Old Plating": {"+1 Bartali Sailboat: Old Plating": 1, "Black Stone": 2},
	"+1 Bartali Sailboat: Old Plating": {"Bartali Sailboat: Old Plating": 1, "Black Stone": 1},
	"+10 Bartali Sailboat: Old Cannon": {"+9 Bartali Sailboat: Old Cannon": 1, "Black Stone": 10},
	"+9 Bartali Sailboat: Old Cannon": {"+8 Bartali Sailboat: Old Cannon": 1, "Black Stone": 9},
	"+8 Bartali Sailboat: Old Cannon": {"+7 Bartali Sailboat: Old Cannon": 1, "Black Stone": 8},
	"+7 Bartali Sailboat: Old Cannon": {"+6 Bartali Sailboat: Old Cannon": 1, "Black Stone": 7},
	"+6 Bartali Sailboat: Old Cannon": {"+5 Bartali Sailboat: Old Cannon": 1, "Black Stone": 6},
	"+5 Bartali Sailboat: Old Cannon": {"+4 Bartali Sailboat: Old Cannon": 1, "Black Stone": 5},
	"+4 Bartali Sailboat: Old Cannon": {"+3 Bartali Sailboat: Old Cannon": 1, "Black Stone": 4},
	"+3 Bartali Sailboat: Old Cannon": {"+2 Bartali Sailboat: Old Cannon": 1, "Black Stone": 3},
	"+2 Bartali Sailboat: Old Cannon": {"+1 Bartali Sailboat: Old Cannon": 1, "Black Stone": 2},
	"+1 Bartali Sailboat: Old Cannon": {"Bartali Sailboat: Old Cannon": 1, "Black Stone": 1},
	"+10 Bartali Sailboat: Old Wind Sail": {"+9 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 10},
	"+9 Bartali Sailboat: Old Wind Sail": {"+8 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 9},
	"+8 Bartali Sailboat: Old Wind Sail": {"+7 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 8},
	"+7 Bartali Sailboat: Old Wind Sail": {"+6 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 7},
	"+6 Bartali Sailboat: Old Wind Sail": {"+5 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 6},
	"+5 Bartali Sailboat: Old Wind Sail": {"+4 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 5},
	"+4 Bartali Sailboat: Old Wind Sail": {"+3 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 4},
	"+3 Bartali Sailboat: Old Wind Sail": {"+2 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 3},
	"+2 Bartali Sailboat: Old Wind Sail": {"+1 Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 2},
	"+1 Bartali Sailboat: Old Wind Sail": {"Bartali Sailboat: Old Wind Sail": 1, "Black Stone": 1},

	"+10 Epheria: Old Figurehead": {"+9 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+9 Epheria: Old Figurehead": {"+8 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+8 Epheria: Old Figurehead": {"+7 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+7 Epheria: Old Figurehead": {"+6 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+6 Epheria: Old Figurehead": {"+5 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+5 Epheria: Old Figurehead": {"+4 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+4 Epheria: Old Figurehead": {"+3 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+3 Epheria: Old Figurehead": {"+2 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+2 Epheria: Old Figurehead": {"+1 Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+1 Epheria: Old Figurehead": {"Epheria: Old Figurehead": 1, "Tidal Black Stone": 1},
	"+10 Epheria: Old Plating": {"+9 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+9 Epheria: Old Plating": {"+8 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+8 Epheria: Old Plating": {"+7 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+7 Epheria: Old Plating": {"+6 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+6 Epheria: Old Plating": {"+5 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+5 Epheria: Old Plating": {"+4 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+4 Epheria: Old Plating": {"+3 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+3 Epheria: Old Plating": {"+2 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+2 Epheria: Old Plating": {"+1 Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+1 Epheria: Old Plating": {"Epheria: Old Plating": 1, "Tidal Black Stone": 1},
	"+10 Epheria: Old Cannon": {"+9 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+9 Epheria: Old Cannon": {"+8 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+8 Epheria: Old Cannon": {"+7 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+7 Epheria: Old Cannon": {"+6 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+6 Epheria: Old Cannon": {"+5 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+5 Epheria: Old Cannon": {"+4 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+4 Epheria: Old Cannon": {"+3 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+3 Epheria: Old Cannon": {"+2 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+2 Epheria: Old Cannon": {"+1 Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+1 Epheria: Old Cannon": {"Epheria: Old Cannon": 1, "Tidal Black Stone": 1},
	"+10 Epheria: Old Wind Sail": {"+9 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+9 Epheria: Old Wind Sail": {"+8 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+8 Epheria: Old Wind Sail": {"+7 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+7 Epheria: Old Wind Sail": {"+6 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+6 Epheria: Old Wind Sail": {"+5 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+5 Epheria: Old Wind Sail": {"+4 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+4 Epheria: Old Wind Sail": {"+3 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+3 Epheria: Old Wind Sail": {"+2 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+2 Epheria: Old Wind Sail": {"+1 Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},
	"+1 Epheria: Old Wind Sail": {"Epheria: Old Wind Sail": 1, "Tidal Black Stone": 1},

	"+10 Epheria Caravel: Brass Figurehead": {"+9 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Brass Figurehead": {"+8 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Brass Figurehead": {"+7 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Brass Figurehead": {"+6 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Brass Figurehead": {"+5 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Brass Figurehead": {"+4 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Brass Figurehead": {"+3 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Brass Figurehead": {"+2 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Brass Figurehead": {"+1 Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Brass Figurehead": {"Epheria Caravel: Brass Figurehead": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: Upgraded Plating": {"+9 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Upgraded Plating": {"+8 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Upgraded Plating": {"+7 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Upgraded Plating": {"+6 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Upgraded Plating": {"+5 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Upgraded Plating": {"+4 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Upgraded Plating": {"+3 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Upgraded Plating": {"+2 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Upgraded Plating": {"+1 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Upgraded Plating": {"Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: Verisha Cannon": {"+9 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Verisha Cannon": {"+8 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Verisha Cannon": {"+7 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Verisha Cannon": {"+6 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Verisha Cannon": {"+5 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Verisha Cannon": {"+4 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Verisha Cannon": {"+3 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Verisha Cannon": {"+2 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Verisha Cannon": {"+1 Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Verisha Cannon": {"Epheria Caravel: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: White Wind Sail": {"+9 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: White Wind Sail": {"+8 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: White Wind Sail": {"+7 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: White Wind Sail": {"+6 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: White Wind Sail": {"+5 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: White Wind Sail": {"+4 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: White Wind Sail": {"+3 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: White Wind Sail": {"+2 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: White Wind Sail": {"+1 Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: White Wind Sail": {"Epheria Caravel: White Wind Sail": 1, "Tidal Black Stone": 1},

	"+10 Epheria Galleass: White Horn Figurehead": {"+9 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: White Horn Figurehead": {"+8 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: White Horn Figurehead": {"+7 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: White Horn Figurehead": {"+6 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: White Horn Figurehead": {"+5 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: White Horn Figurehead": {"+4 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: White Horn Figurehead": {"+3 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: White Horn Figurehead": {"+2 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: White Horn Figurehead": {"+1 Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: White Horn Figurehead": {"Epheria Galleass: White Horn Figurehead": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: Upgraded Plating": {"+9 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Upgraded Plating": {"+8 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Upgraded Plating": {"+7 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Upgraded Plating": {"+6 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Upgraded Plating": {"+5 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Upgraded Plating": {"+4 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Upgraded Plating": {"+3 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Upgraded Plating": {"+2 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Upgraded Plating": {"+1 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Upgraded Plating": {"Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: Verisha Cannon": {"+9 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Verisha Cannon": {"+8 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Verisha Cannon": {"+7 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Verisha Cannon": {"+6 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Verisha Cannon": {"+5 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Verisha Cannon": {"+4 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Verisha Cannon": {"+3 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Verisha Cannon": {"+2 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Verisha Cannon": {"+1 Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Verisha Cannon": {"Epheria Galleass: Verisha Cannon": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: White Wind Sail": {"+9 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: White Wind Sail": {"+8 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: White Wind Sail": {"+7 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: White Wind Sail": {"+6 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: White Wind Sail": {"+5 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: White Wind Sail": {"+4 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: White Wind Sail": {"+3 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: White Wind Sail": {"+2 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: White Wind Sail": {"+1 Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: White Wind Sail": {"Epheria Galleass: White Wind Sail": 1, "Tidal Black Stone": 1},

	"+10 Epheria Caravel: Black Dragon Figurehead": {"+9 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Black Dragon Figurehead": {"+8 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Black Dragon Figurehead": {"+7 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Black Dragon Figurehead": {"+6 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Black Dragon Figurehead": {"+5 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Black Dragon Figurehead": {"+4 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Black Dragon Figurehead": {"+3 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Black Dragon Figurehead": {"+2 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Black Dragon Figurehead": {"+1 Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Black Dragon Figurehead": {"Epheria Caravel: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: Upgraded Plating": {"+9 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Upgraded Plating": {"+8 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Upgraded Plating": {"+7 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Upgraded Plating": {"+6 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Upgraded Plating": {"+5 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Upgraded Plating": {"+4 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Upgraded Plating": {"+3 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Upgraded Plating": {"+2 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Upgraded Plating": {"+1 Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Upgraded Plating": {"Epheria Caravel: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: Mayna Cannon": {"+9 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Mayna Cannon": {"+8 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Mayna Cannon": {"+7 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Mayna Cannon": {"+6 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Mayna Cannon": {"+5 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Mayna Cannon": {"+4 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Mayna Cannon": {"+3 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Mayna Cannon": {"+2 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Mayna Cannon": {"+1 Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Mayna Cannon": {"Epheria Caravel: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+10 Epheria Caravel: Stratus Wind Sail": {"+9 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+9 Epheria Caravel: Stratus Wind Sail": {"+8 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+8 Epheria Caravel: Stratus Wind Sail": {"+7 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+7 Epheria Caravel: Stratus Wind Sail": {"+6 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+6 Epheria Caravel: Stratus Wind Sail": {"+5 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+5 Epheria Caravel: Stratus Wind Sail": {"+4 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+4 Epheria Caravel: Stratus Wind Sail": {"+3 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+3 Epheria Caravel: Stratus Wind Sail": {"+2 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+2 Epheria Caravel: Stratus Wind Sail": {"+1 Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+1 Epheria Caravel: Stratus Wind Sail": {"Epheria Caravel: Stratus Wind Sail": 1, "Tidal Black Stone": 1},

	"+10 Epheria Galleass: Black Dragon Figurehead": {"+9 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Black Dragon Figurehead": {"+8 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Black Dragon Figurehead": {"+7 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Black Dragon Figurehead": {"+6 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Black Dragon Figurehead": {"+5 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Black Dragon Figurehead": {"+4 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Black Dragon Figurehead": {"+3 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Black Dragon Figurehead": {"+2 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Black Dragon Figurehead": {"+1 Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Black Dragon Figurehead": {"Epheria Galleass: Black Dragon Figurehead": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: Upgraded Plating": {"+9 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Upgraded Plating": {"+8 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Upgraded Plating": {"+7 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Upgraded Plating": {"+6 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Upgraded Plating": {"+5 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Upgraded Plating": {"+4 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Upgraded Plating": {"+3 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Upgraded Plating": {"+2 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Upgraded Plating": {"+1 Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Upgraded Plating": {"Epheria Galleass: Upgraded Plating": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: Mayna Cannon": {"+9 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Mayna Cannon": {"+8 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Mayna Cannon": {"+7 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Mayna Cannon": {"+6 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Mayna Cannon": {"+5 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Mayna Cannon": {"+4 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Mayna Cannon": {"+3 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Mayna Cannon": {"+2 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Mayna Cannon": {"+1 Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Mayna Cannon": {"Epheria Galleass: Mayna Cannon": 1, "Tidal Black Stone": 1},
	"+10 Epheria Galleass: Stratus Wind Sail": {"+9 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+9 Epheria Galleass: Stratus Wind Sail": {"+8 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+8 Epheria Galleass: Stratus Wind Sail": {"+7 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+7 Epheria Galleass: Stratus Wind Sail": {"+6 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+6 Epheria Galleass: Stratus Wind Sail": {"+5 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 2},
	"+5 Epheria Galleass: Stratus Wind Sail": {"+4 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+4 Epheria Galleass: Stratus Wind Sail": {"+3 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+3 Epheria Galleass: Stratus Wind Sail": {"+2 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+2 Epheria Galleass: Stratus Wind Sail": {"+1 Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 1},
	"+1 Epheria Galleass: Stratus Wind Sail": {"Epheria Galleass: Stratus Wind Sail": 1, "Tidal Black Stone": 1},

	// ===== Chiro's part materials (craftable via Processing; also buyable for 350 Crow Coins) =====
	"Violent Wave Plywood": {
		"Violent Sea Monster's Scale": 1,
		"Saltwater Crocodile's Scale": 1
	},
	"Delicately Polished Support": {
		"Violent Sea Monster's Bone": 1,
		"Starlight Hardener": 1
	},
	"Wave Residue Adhesive": {
		"Violent Sea Monster's Ooze": 1,
		"Starlight Emulsifier": 1
	},

	// ===== Epheria Carrack: Chiro's parts (blue) - crafted at Chiro's Ship Part Workshop, Iliya Island =====
	"Epheria Carrack: Advance (Chiro's Cannon)": {
		"+10 Epheria Carrack: Toro Cannon": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Cannon": 10,
		"Epheria Carrack Parts Upgrade Permit: Advance": 1
	},
	"Epheria Carrack: Advance (Chiro's Sail)": {
		"+10 Epheria Carrack: Toro Sail": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Sail": 10,
		"Epheria Carrack Parts Upgrade Permit: Advance": 1
	},
	"Epheria Carrack: Advance (Chiro's Figurehead)": {
		"+10 Epheria Carrack: Toro Figurehead": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Figurehead": 10,
		"Epheria Carrack Parts Upgrade Permit: Advance": 1
	},
	"Epheria Carrack: Advance (Chiro's Black Plating)": {
		"+10 Epheria Carrack: Toro Plating": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Black Plating": 10,
		"Epheria Carrack Parts Upgrade Permit: Advance": 1
	},
	"Epheria Carrack: Balance (Chiro's Cannon)": {
		"+10 Epheria Carrack: Toro Cannon": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Cannon": 10,
		"Epheria Carrack Parts Upgrade Permit: Balance": 1
	},
	"Epheria Carrack: Balance (Chiro's Sail)": {
		"+10 Epheria Carrack: Toro Sail": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Sail": 10,
		"Epheria Carrack Parts Upgrade Permit: Balance": 1
	},
	"Epheria Carrack: Balance (Chiro's Figurehead)": {
		"+10 Epheria Carrack: Toro Figurehead": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Figurehead": 10,
		"Epheria Carrack Parts Upgrade Permit: Balance": 1
	},
	"Epheria Carrack: Balance (Chiro's Black Plating)": {
		"+10 Epheria Carrack: Toro Plating": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Black Plating": 10,
		"Epheria Carrack Parts Upgrade Permit: Balance": 1
	},
	"Epheria Carrack: Volante (Chiro's Cannon)": {
		"+10 Epheria Carrack: Toro Cannon": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Cannon": 10,
		"Epheria Carrack Parts Upgrade Permit: Volante": 1
	},
	"Epheria Carrack: Volante (Chiro's Sail)": {
		"+10 Epheria Carrack: Toro Sail": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Sail": 10,
		"Epheria Carrack Parts Upgrade Permit: Volante": 1
	},
	"Epheria Carrack: Volante (Chiro's Figurehead)": {
		"+10 Epheria Carrack: Toro Figurehead": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Figurehead": 10,
		"Epheria Carrack Parts Upgrade Permit: Volante": 1
	},
	"Epheria Carrack: Volante (Chiro's Black Plating)": {
		"+10 Epheria Carrack: Toro Plating": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Black Plating": 10,
		"Epheria Carrack Parts Upgrade Permit: Volante": 1
	},
	"Epheria Carrack: Valor (Chiro's Cannon)": {
		"+10 Epheria Carrack: Toro Cannon": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Cannon": 10,
		"Epheria Carrack Parts Upgrade Permit: Valor": 1
	},
	"Epheria Carrack: Valor (Chiro's Sail)": {
		"+10 Epheria Carrack: Toro Sail": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Sail": 10,
		"Epheria Carrack Parts Upgrade Permit: Valor": 1
	},
	"Epheria Carrack: Valor (Chiro's Figurehead)": {
		"+10 Epheria Carrack: Toro Figurehead": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Figurehead": 10,
		"Epheria Carrack Parts Upgrade Permit: Valor": 1
	},
	"Epheria Carrack: Valor (Chiro's Black Plating)": {
		"+10 Epheria Carrack: Toro Plating": 1,
		"Violent Wave Plywood": 100,
		"Delicately Polished Support": 100,
		"Wave Residue Adhesive": 100,
		"Blueprint: Chiro's Black Plating": 10,
		"Epheria Carrack Parts Upgrade Permit: Valor": 1
	},

	// Toro parts (green): Tidal Black Stone x20 up to +5, x30 from +6 -- per
	// the per-level table on bdocodex, which prices the +4 -> +5 attempt at 20.
	"+10 Epheria Carrack: Toro Cannon": {"+9 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 30},
	"+9 Epheria Carrack: Toro Cannon": {"+8 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 30},
	"+8 Epheria Carrack: Toro Cannon": {"+7 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 30},
	"+7 Epheria Carrack: Toro Cannon": {"+6 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 30},
	"+6 Epheria Carrack: Toro Cannon": {"+5 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 30},
	"+5 Epheria Carrack: Toro Cannon": {"+4 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 20},
	"+4 Epheria Carrack: Toro Cannon": {"+3 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 20},
	"+3 Epheria Carrack: Toro Cannon": {"+2 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 20},
	"+2 Epheria Carrack: Toro Cannon": {"+1 Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 20},
	"+1 Epheria Carrack: Toro Cannon": {"Epheria Carrack: Toro Cannon": 1, "Tidal Black Stone": 20},
	"+10 Epheria Carrack: Toro Sail": {"+9 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 30},
	"+9 Epheria Carrack: Toro Sail": {"+8 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 30},
	"+8 Epheria Carrack: Toro Sail": {"+7 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 30},
	"+7 Epheria Carrack: Toro Sail": {"+6 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 30},
	"+6 Epheria Carrack: Toro Sail": {"+5 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 30},
	"+5 Epheria Carrack: Toro Sail": {"+4 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 20},
	"+4 Epheria Carrack: Toro Sail": {"+3 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 20},
	"+3 Epheria Carrack: Toro Sail": {"+2 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 20},
	"+2 Epheria Carrack: Toro Sail": {"+1 Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 20},
	"+1 Epheria Carrack: Toro Sail": {"Epheria Carrack: Toro Sail": 1, "Tidal Black Stone": 20},
	"+10 Epheria Carrack: Toro Figurehead": {"+9 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 30},
	"+9 Epheria Carrack: Toro Figurehead": {"+8 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 30},
	"+8 Epheria Carrack: Toro Figurehead": {"+7 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 30},
	"+7 Epheria Carrack: Toro Figurehead": {"+6 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 30},
	"+6 Epheria Carrack: Toro Figurehead": {"+5 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 30},
	"+5 Epheria Carrack: Toro Figurehead": {"+4 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 20},
	"+4 Epheria Carrack: Toro Figurehead": {"+3 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 20},
	"+3 Epheria Carrack: Toro Figurehead": {"+2 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 20},
	"+2 Epheria Carrack: Toro Figurehead": {"+1 Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 20},
	"+1 Epheria Carrack: Toro Figurehead": {"Epheria Carrack: Toro Figurehead": 1, "Tidal Black Stone": 20},
	"+10 Epheria Carrack: Toro Plating": {"+9 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 30},
	"+9 Epheria Carrack: Toro Plating": {"+8 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 30},
	"+8 Epheria Carrack: Toro Plating": {"+7 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 30},
	"+7 Epheria Carrack: Toro Plating": {"+6 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 30},
	"+6 Epheria Carrack: Toro Plating": {"+5 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 30},
	"+5 Epheria Carrack: Toro Plating": {"+4 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 20},
	"+4 Epheria Carrack: Toro Plating": {"+3 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 20},
	"+3 Epheria Carrack: Toro Plating": {"+2 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 20},
	"+2 Epheria Carrack: Toro Plating": {"+1 Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 20},
	"+1 Epheria Carrack: Toro Plating": {"Epheria Carrack: Toro Plating": 1, "Tidal Black Stone": 20},

	// Chiro parts (blue) enhancement: Tidal Black Stone x50 per level (needed for the upcoming yellow parts)
	"+10 Epheria Carrack: Advance (Chiro's Cannon)": {"+9 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Advance (Chiro's Cannon)": {"+8 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Advance (Chiro's Cannon)": {"+7 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Advance (Chiro's Cannon)": {"+6 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Advance (Chiro's Cannon)": {"+5 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Advance (Chiro's Cannon)": {"+4 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Advance (Chiro's Cannon)": {"+3 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Advance (Chiro's Cannon)": {"+2 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Advance (Chiro's Cannon)": {"+1 Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Advance (Chiro's Cannon)": {"Epheria Carrack: Advance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Advance (Chiro's Sail)": {"+9 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Advance (Chiro's Sail)": {"+8 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Advance (Chiro's Sail)": {"+7 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Advance (Chiro's Sail)": {"+6 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Advance (Chiro's Sail)": {"+5 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Advance (Chiro's Sail)": {"+4 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Advance (Chiro's Sail)": {"+3 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Advance (Chiro's Sail)": {"+2 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Advance (Chiro's Sail)": {"+1 Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Advance (Chiro's Sail)": {"Epheria Carrack: Advance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Advance (Chiro's Figurehead)": {"+9 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Advance (Chiro's Figurehead)": {"+8 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Advance (Chiro's Figurehead)": {"+7 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Advance (Chiro's Figurehead)": {"+6 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Advance (Chiro's Figurehead)": {"+5 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Advance (Chiro's Figurehead)": {"+4 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Advance (Chiro's Figurehead)": {"+3 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Advance (Chiro's Figurehead)": {"+2 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Advance (Chiro's Figurehead)": {"+1 Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Advance (Chiro's Figurehead)": {"Epheria Carrack: Advance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Advance (Chiro's Black Plating)": {"+9 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Advance (Chiro's Black Plating)": {"+8 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Advance (Chiro's Black Plating)": {"+7 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Advance (Chiro's Black Plating)": {"+6 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Advance (Chiro's Black Plating)": {"+5 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Advance (Chiro's Black Plating)": {"+4 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Advance (Chiro's Black Plating)": {"+3 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Advance (Chiro's Black Plating)": {"+2 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Advance (Chiro's Black Plating)": {"+1 Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Advance (Chiro's Black Plating)": {"Epheria Carrack: Advance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Balance (Chiro's Cannon)": {"+9 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Balance (Chiro's Cannon)": {"+8 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Balance (Chiro's Cannon)": {"+7 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Balance (Chiro's Cannon)": {"+6 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Balance (Chiro's Cannon)": {"+5 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Balance (Chiro's Cannon)": {"+4 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Balance (Chiro's Cannon)": {"+3 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Balance (Chiro's Cannon)": {"+2 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Balance (Chiro's Cannon)": {"+1 Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Balance (Chiro's Cannon)": {"Epheria Carrack: Balance (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Balance (Chiro's Sail)": {"+9 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Balance (Chiro's Sail)": {"+8 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Balance (Chiro's Sail)": {"+7 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Balance (Chiro's Sail)": {"+6 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Balance (Chiro's Sail)": {"+5 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Balance (Chiro's Sail)": {"+4 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Balance (Chiro's Sail)": {"+3 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Balance (Chiro's Sail)": {"+2 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Balance (Chiro's Sail)": {"+1 Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Balance (Chiro's Sail)": {"Epheria Carrack: Balance (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Balance (Chiro's Figurehead)": {"+9 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Balance (Chiro's Figurehead)": {"+8 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Balance (Chiro's Figurehead)": {"+7 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Balance (Chiro's Figurehead)": {"+6 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Balance (Chiro's Figurehead)": {"+5 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Balance (Chiro's Figurehead)": {"+4 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Balance (Chiro's Figurehead)": {"+3 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Balance (Chiro's Figurehead)": {"+2 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Balance (Chiro's Figurehead)": {"+1 Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Balance (Chiro's Figurehead)": {"Epheria Carrack: Balance (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Balance (Chiro's Black Plating)": {"+9 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Balance (Chiro's Black Plating)": {"+8 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Balance (Chiro's Black Plating)": {"+7 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Balance (Chiro's Black Plating)": {"+6 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Balance (Chiro's Black Plating)": {"+5 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Balance (Chiro's Black Plating)": {"+4 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Balance (Chiro's Black Plating)": {"+3 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Balance (Chiro's Black Plating)": {"+2 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Balance (Chiro's Black Plating)": {"+1 Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Balance (Chiro's Black Plating)": {"Epheria Carrack: Balance (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Volante (Chiro's Cannon)": {"+9 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Volante (Chiro's Cannon)": {"+8 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Volante (Chiro's Cannon)": {"+7 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Volante (Chiro's Cannon)": {"+6 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Volante (Chiro's Cannon)": {"+5 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Volante (Chiro's Cannon)": {"+4 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Volante (Chiro's Cannon)": {"+3 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Volante (Chiro's Cannon)": {"+2 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Volante (Chiro's Cannon)": {"+1 Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Volante (Chiro's Cannon)": {"Epheria Carrack: Volante (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Volante (Chiro's Sail)": {"+9 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Volante (Chiro's Sail)": {"+8 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Volante (Chiro's Sail)": {"+7 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Volante (Chiro's Sail)": {"+6 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Volante (Chiro's Sail)": {"+5 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Volante (Chiro's Sail)": {"+4 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Volante (Chiro's Sail)": {"+3 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Volante (Chiro's Sail)": {"+2 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Volante (Chiro's Sail)": {"+1 Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Volante (Chiro's Sail)": {"Epheria Carrack: Volante (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Volante (Chiro's Figurehead)": {"+9 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Volante (Chiro's Figurehead)": {"+8 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Volante (Chiro's Figurehead)": {"+7 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Volante (Chiro's Figurehead)": {"+6 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Volante (Chiro's Figurehead)": {"+5 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Volante (Chiro's Figurehead)": {"+4 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Volante (Chiro's Figurehead)": {"+3 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Volante (Chiro's Figurehead)": {"+2 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Volante (Chiro's Figurehead)": {"+1 Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Volante (Chiro's Figurehead)": {"Epheria Carrack: Volante (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Volante (Chiro's Black Plating)": {"+9 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Volante (Chiro's Black Plating)": {"+8 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Volante (Chiro's Black Plating)": {"+7 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Volante (Chiro's Black Plating)": {"+6 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Volante (Chiro's Black Plating)": {"+5 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Volante (Chiro's Black Plating)": {"+4 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Volante (Chiro's Black Plating)": {"+3 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Volante (Chiro's Black Plating)": {"+2 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Volante (Chiro's Black Plating)": {"+1 Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Volante (Chiro's Black Plating)": {"Epheria Carrack: Volante (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Valor (Chiro's Cannon)": {"+9 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Valor (Chiro's Cannon)": {"+8 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Valor (Chiro's Cannon)": {"+7 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Valor (Chiro's Cannon)": {"+6 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Valor (Chiro's Cannon)": {"+5 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Valor (Chiro's Cannon)": {"+4 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Valor (Chiro's Cannon)": {"+3 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Valor (Chiro's Cannon)": {"+2 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Valor (Chiro's Cannon)": {"+1 Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Valor (Chiro's Cannon)": {"Epheria Carrack: Valor (Chiro's Cannon)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Valor (Chiro's Sail)": {"+9 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Valor (Chiro's Sail)": {"+8 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Valor (Chiro's Sail)": {"+7 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Valor (Chiro's Sail)": {"+6 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Valor (Chiro's Sail)": {"+5 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Valor (Chiro's Sail)": {"+4 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Valor (Chiro's Sail)": {"+3 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Valor (Chiro's Sail)": {"+2 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Valor (Chiro's Sail)": {"+1 Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Valor (Chiro's Sail)": {"Epheria Carrack: Valor (Chiro's Sail)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Valor (Chiro's Figurehead)": {"+9 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Valor (Chiro's Figurehead)": {"+8 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Valor (Chiro's Figurehead)": {"+7 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Valor (Chiro's Figurehead)": {"+6 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Valor (Chiro's Figurehead)": {"+5 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Valor (Chiro's Figurehead)": {"+4 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Valor (Chiro's Figurehead)": {"+3 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Valor (Chiro's Figurehead)": {"+2 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Valor (Chiro's Figurehead)": {"+1 Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Valor (Chiro's Figurehead)": {"Epheria Carrack: Valor (Chiro's Figurehead)": 1, "Tidal Black Stone": 50},
	"+10 Epheria Carrack: Valor (Chiro's Black Plating)": {"+9 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+9 Epheria Carrack: Valor (Chiro's Black Plating)": {"+8 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+8 Epheria Carrack: Valor (Chiro's Black Plating)": {"+7 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+7 Epheria Carrack: Valor (Chiro's Black Plating)": {"+6 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+6 Epheria Carrack: Valor (Chiro's Black Plating)": {"+5 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+5 Epheria Carrack: Valor (Chiro's Black Plating)": {"+4 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+4 Epheria Carrack: Valor (Chiro's Black Plating)": {"+3 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+3 Epheria Carrack: Valor (Chiro's Black Plating)": {"+2 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+2 Epheria Carrack: Valor (Chiro's Black Plating)": {"+1 Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},
	"+1 Epheria Carrack: Valor (Chiro's Black Plating)": {"Epheria Carrack: Valor (Chiro's Black Plating)": 1, "Tidal Black Stone": 50},

	// ---- Panokseon gear -------------------------------------------
	// Haemo's parts are bought from the Crow Coin Shop at 10,000 each and
	// enhanced; the +10 then becomes a Byukgye's part, exactly as Toro
	// becomes Chiro on the Carrack.
	"Panokseon: Byukgye's Enhanced Cannon": {
		"+10 Panokseon: Haemo's Cannon": 1,
		"Blueprint: Byukgye's Enhanced Cannon": 10,
		"Finely Polished Pine Plywood": 50,
		"Wave Residue Adhesive": 50,
		"Delicately Polished Support": 50,
		"Panokseon Enhancement Parts Upgrade Permit": 1
	},
	"Panokseon: Byukgye's Enhanced Sail": {
		"+10 Panokseon: Haemo's Sail": 1,
		"Blueprint: Byukgye's Enhanced Sail": 10,
		"Finely Polished Pine Plywood": 50,
		"Wave Residue Adhesive": 50,
		"Delicately Polished Support": 50,
		"Panokseon Enhancement Parts Upgrade Permit": 1
	},
	"Panokseon: Byukgye's Enhanced Figurehead": {
		"+10 Panokseon: Haemo's Figurehead": 1,
		"Blueprint: Byukgye's Enhanced Figurehead": 10,
		"Finely Polished Pine Plywood": 50,
		"Wave Residue Adhesive": 50,
		"Delicately Polished Support": 50,
		"Panokseon Enhancement Parts Upgrade Permit": 1
	},
	"Panokseon: Byukgye's Enhanced Plating": {
		"+10 Panokseon: Haemo's Plating": 1,
		"Blueprint: Byukgye's Enhanced Plating": 10,
		"Finely Polished Pine Plywood": 50,
		"Wave Residue Adhesive": 50,
		"Delicately Polished Support": 50,
		"Panokseon Enhancement Parts Upgrade Permit": 1
	},

	// Haemo's (green): Tidal Black Stone x20 up to +5, x30 from +6.
	"+10 Panokseon: Haemo's Cannon": {"+9 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 30},
	"+9 Panokseon: Haemo's Cannon": {"+8 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 30},
	"+8 Panokseon: Haemo's Cannon": {"+7 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 30},
	"+7 Panokseon: Haemo's Cannon": {"+6 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 30},
	"+6 Panokseon: Haemo's Cannon": {"+5 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 30},
	"+5 Panokseon: Haemo's Cannon": {"+4 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 20},
	"+4 Panokseon: Haemo's Cannon": {"+3 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 20},
	"+3 Panokseon: Haemo's Cannon": {"+2 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 20},
	"+2 Panokseon: Haemo's Cannon": {"+1 Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 20},
	"+1 Panokseon: Haemo's Cannon": {"Panokseon: Haemo's Cannon": 1, "Tidal Black Stone": 20},
	"+10 Panokseon: Haemo's Sail": {"+9 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 30},
	"+9 Panokseon: Haemo's Sail": {"+8 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 30},
	"+8 Panokseon: Haemo's Sail": {"+7 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 30},
	"+7 Panokseon: Haemo's Sail": {"+6 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 30},
	"+6 Panokseon: Haemo's Sail": {"+5 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 30},
	"+5 Panokseon: Haemo's Sail": {"+4 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 20},
	"+4 Panokseon: Haemo's Sail": {"+3 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 20},
	"+3 Panokseon: Haemo's Sail": {"+2 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 20},
	"+2 Panokseon: Haemo's Sail": {"+1 Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 20},
	"+1 Panokseon: Haemo's Sail": {"Panokseon: Haemo's Sail": 1, "Tidal Black Stone": 20},
	"+10 Panokseon: Haemo's Figurehead": {"+9 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 30},
	"+9 Panokseon: Haemo's Figurehead": {"+8 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 30},
	"+8 Panokseon: Haemo's Figurehead": {"+7 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 30},
	"+7 Panokseon: Haemo's Figurehead": {"+6 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 30},
	"+6 Panokseon: Haemo's Figurehead": {"+5 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 30},
	"+5 Panokseon: Haemo's Figurehead": {"+4 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 20},
	"+4 Panokseon: Haemo's Figurehead": {"+3 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 20},
	"+3 Panokseon: Haemo's Figurehead": {"+2 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 20},
	"+2 Panokseon: Haemo's Figurehead": {"+1 Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 20},
	"+1 Panokseon: Haemo's Figurehead": {"Panokseon: Haemo's Figurehead": 1, "Tidal Black Stone": 20},
	"+10 Panokseon: Haemo's Plating": {"+9 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 30},
	"+9 Panokseon: Haemo's Plating": {"+8 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 30},
	"+8 Panokseon: Haemo's Plating": {"+7 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 30},
	"+7 Panokseon: Haemo's Plating": {"+6 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 30},
	"+6 Panokseon: Haemo's Plating": {"+5 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 30},
	"+5 Panokseon: Haemo's Plating": {"+4 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 20},
	"+4 Panokseon: Haemo's Plating": {"+3 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 20},
	"+3 Panokseon: Haemo's Plating": {"+2 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 20},
	"+2 Panokseon: Haemo's Plating": {"+1 Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 20},
	"+1 Panokseon: Haemo's Plating": {"Panokseon: Haemo's Plating": 1, "Tidal Black Stone": 20},

	// Byukgye's (blue): Tidal Black Stone x50 at every level.
	"+10 Panokseon: Byukgye's Enhanced Cannon": {"+9 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+9 Panokseon: Byukgye's Enhanced Cannon": {"+8 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+8 Panokseon: Byukgye's Enhanced Cannon": {"+7 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+7 Panokseon: Byukgye's Enhanced Cannon": {"+6 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+6 Panokseon: Byukgye's Enhanced Cannon": {"+5 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+5 Panokseon: Byukgye's Enhanced Cannon": {"+4 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+4 Panokseon: Byukgye's Enhanced Cannon": {"+3 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+3 Panokseon: Byukgye's Enhanced Cannon": {"+2 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+2 Panokseon: Byukgye's Enhanced Cannon": {"+1 Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+1 Panokseon: Byukgye's Enhanced Cannon": {"Panokseon: Byukgye's Enhanced Cannon": 1, "Tidal Black Stone": 50},
	"+10 Panokseon: Byukgye's Enhanced Sail": {"+9 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+9 Panokseon: Byukgye's Enhanced Sail": {"+8 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+8 Panokseon: Byukgye's Enhanced Sail": {"+7 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+7 Panokseon: Byukgye's Enhanced Sail": {"+6 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+6 Panokseon: Byukgye's Enhanced Sail": {"+5 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+5 Panokseon: Byukgye's Enhanced Sail": {"+4 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+4 Panokseon: Byukgye's Enhanced Sail": {"+3 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+3 Panokseon: Byukgye's Enhanced Sail": {"+2 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+2 Panokseon: Byukgye's Enhanced Sail": {"+1 Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+1 Panokseon: Byukgye's Enhanced Sail": {"Panokseon: Byukgye's Enhanced Sail": 1, "Tidal Black Stone": 50},
	"+10 Panokseon: Byukgye's Enhanced Figurehead": {"+9 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+9 Panokseon: Byukgye's Enhanced Figurehead": {"+8 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+8 Panokseon: Byukgye's Enhanced Figurehead": {"+7 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+7 Panokseon: Byukgye's Enhanced Figurehead": {"+6 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+6 Panokseon: Byukgye's Enhanced Figurehead": {"+5 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+5 Panokseon: Byukgye's Enhanced Figurehead": {"+4 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+4 Panokseon: Byukgye's Enhanced Figurehead": {"+3 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+3 Panokseon: Byukgye's Enhanced Figurehead": {"+2 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+2 Panokseon: Byukgye's Enhanced Figurehead": {"+1 Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+1 Panokseon: Byukgye's Enhanced Figurehead": {"Panokseon: Byukgye's Enhanced Figurehead": 1, "Tidal Black Stone": 50},
	"+10 Panokseon: Byukgye's Enhanced Plating": {"+9 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+9 Panokseon: Byukgye's Enhanced Plating": {"+8 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+8 Panokseon: Byukgye's Enhanced Plating": {"+7 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+7 Panokseon: Byukgye's Enhanced Plating": {"+6 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+6 Panokseon: Byukgye's Enhanced Plating": {"+5 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+5 Panokseon: Byukgye's Enhanced Plating": {"+4 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+4 Panokseon: Byukgye's Enhanced Plating": {"+3 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+3 Panokseon: Byukgye's Enhanced Plating": {"+2 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+2 Panokseon: Byukgye's Enhanced Plating": {"+1 Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
	"+1 Panokseon: Byukgye's Enhanced Plating": {"Panokseon: Byukgye's Enhanced Plating": 1, "Tidal Black Stone": 50},
};
