// Generated by tools/build-changelog.mjs from js/about.js -- do not edit.
//
// What the page needs to know at boot about the release notes: which
// release this build is, and the newest working entry. The notes
// themselves stay in about.js, imported when they are opened.

/** The release this build is; what the What's New dialog is keyed on. */
export const RELEASE = "1.5.1";

/** The newest diary entry, as the "seen" key and as its title. */
export const LATEST = "2026-10-04:Fixes from the fleet: numbers, barter runs and a page that holds still";
export const LATEST_TITLE = "Fixes from the fleet: numbers, barter runs and a page that holds still";
