// Generated by tools/build-changelog.mjs from js/about.js -- do not edit.
//
// What the page needs to know at boot about the release notes: which
// release this build is, and the newest working entry. The notes
// themselves stay in about.js, imported when they are opened.

/** The release this build is; what the What's New dialog is keyed on. */
export const RELEASE = "1.5";

/** The newest diary entry, as the "seen" key and as its title. */
export const LATEST = "2026-10-01:A sweep of fixes before 1.5";
export const LATEST_TITLE = "A sweep of fixes before 1.5";
