// Generated by tools/build-changelog.mjs from js/about.js -- do not edit.
//
// What the page needs to know at boot about the release notes: which
// release this build is, and the newest working entry. The notes
// themselves stay in about.js, imported when they are opened.

/** The release this build is; what the What's New dialog is keyed on. */
export const RELEASE = "1.5";

/** The newest diary entry, as the "seen" key and as its title. */
export const LATEST = "2026-10-03:The chart’s ship, links that say what they are, and the guide re-shot";
export const LATEST_TITLE = "The chart’s ship, links that say what they are, and the guide re-shot";
