// What every sailor type is called, in each language the game runs in.
//
// The Selected Sailor panel prints the type in angle brackets, and in a
// client set to anything but English it prints it translated. This is
// that translation, so a screenshot read in any language still names
// the type outright rather than leaving it to be guessed from the
// appetite, the cabin cost and the weight.
//
// Read from BDOCodex -- the game's own strings -- by
// tools/fetch-sailor-titles.mjs on 2026-09-11. English is the key, and is
// not repeated inside.

export const TITLES_READ = '2026-09-11';

export const sailorTitles = {
	"Ambitious": {
		"de": "Ehrgeizig",
		"fr": "Ambitieux",
		"ru": "Жадный",
		"es": "Ambicioso",
		"es-419": "Avaricioso",
		"pt": "Ganancioso",
		"ja": "欲張りな",
		"ko": "욕심 있는",
		"zh": "贪心的",
		"zh-Hant": "有野心的",
		"th": "มักใหญ่ใฝ่สูง",
		"tr": "Hırslı",
		"id": "Rakus"
	},
	"Born-in-the-Sea": {
		"de": "Im Meer geboren",
		"fr": "Né en mer",
		"ru": "Рожденный в море",
		"es": "Sangremarina",
		"es-419": "Nacido del Océano",
		"pt": "Nascido no Mar",
		"ja": "海に生まれた",
		"ko": "바다에서 태어난",
		"zh": "出生于大海的",
		"zh-Hant": "出生於大海的",
		"th": "เกิดที่ทะเล",
		"tr": "Denizde Doğmuş",
		"id": "Terlahir di Laut"
	},
	"Calculating": {
		"de": "Berechnend",
		"fr": "Calculateur",
		"ru": "Расчетливый",
		"es": "Calculador",
		"es-419": "Calculador",
		"pt": "Calculista",
		"ja": "計算高い",
		"ko": "계산적인",
		"zh": "心里有数的",
		"zh-Hant": "斤斤計較的",
		"th": "นักคิดคำนวณ",
		"tr": "Hesapçı",
		"id": "Perhitungan"
	},
	"Confident": {
		"de": "Zuversichtlich",
		"fr": "Confiant",
		"ru": "Самоуверенный",
		"es": "Confiado",
		"es-419": "Confiado",
		"pt": "Confiante",
		"ja": "自信ある",
		"ko": "자신있는",
		"zh": "有自信的",
		"zh-Hant": "有自信的",
		"th": "มั่นใจ",
		"tr": "Kendinden Emin",
		"id": "Percaya Diri"
	},
	"Curious": {
		"de": "Neugierig",
		"fr": "Curieux",
		"ru": "Любопытный",
		"es": "Curioso",
		"es-419": "Curioso",
		"pt": "Muito Curioso",
		"ja": "好奇心の強い",
		"ko": "호기심 많은",
		"zh": "好奇心强的",
		"zh-Hant": "好奇心強的",
		"th": "อยากรู้อยากเห็น",
		"tr": "Meraklı",
		"id": "Yang Penasaran"
	},
	"Diligent": {
		"de": "Fleißig",
		"fr": "Scrupuleux",
		"ru": "Добросовестный",
		"es": "Diligente",
		"es-419": "Responsable",
		"pt": "Dedicado",
		"ja": "誠実な",
		"ko": "성실한",
		"zh": "诚实的",
		"zh-Hant": "誠實的",
		"th": "ซื่อสัตย์",
		"tr": "Dürüst",
		"id": "Rajin"
	},
	"Dreaming of a Full Haul": {
		"de": "Träumt vom großen Fang",
		"fr": "Rêve d'une belle pêche",
		"ru": "Мечтательный",
		"es": "Soñando con una gran captura",
		"es-419": "Soñando un Barco Lleno de Peces",
		"pt": "Sonho de Pesca Farta",
		"ja": "満船を夢見る",
		"ko": "만선을 꿈꾸는",
		"zh": "期盼满载的",
		"zh-Hant": "盼著滿載航行的",
		"th": "ใฝ่ฝันถึงการบรรทุก",
		"tr": "Çok Balık Seven",
		"id": "Pemimpi Kapal Penuh"
	},
	"Enamored": {
		"de": "Verliebt",
		"fr": "Amoureux",
		"ru": "Влюбленный",
		"es": "Enamorado",
		"es-419": "Enamorado",
		"pt": "Perdido de Amor",
		"ja": "恋に落ちた",
		"ko": "사랑에 빠진",
		"zh": "陷入爱河的",
		"zh-Hant": "陷入愛河的",
		"th": "ตกหลุมรัก",
		"tr": "Mecnun",
		"id": "Jatuh Cinta"
	},
	"Experienced": {
		"de": "Erfahren",
		"fr": "Expérimenté",
		"ru": "Опытный",
		"es": "Experimentado",
		"es-419": "Experimentado",
		"pt": "Muito Experiente",
		"ja": "経験の多い",
		"ko": "경험 많은",
		"zh": "经验丰富的",
		"zh-Hant": "經驗豐富的",
		"th": "มากประสบการณ์",
		"tr": "Tecrübeli",
		"id": "Yang Berpengalaman"
	},
	"Honest": {
		"de": "Ehrlich",
		"fr": "Honnête",
		"ru": "Честный",
		"es": "Honesto",
		"es-419": "Firme",
		"pt": "Perseverante",
		"ja": "愚直な",
		"ko": "우직한",
		"zh": "憨直的",
		"zh-Hant": "憨直的",
		"th": "ไม่มีเล่ห์เหลี่ยม",
		"tr": "Toy",
		"id": "Lugu"
	},
	"Innocent": {
		"de": "Unschuldig",
		"fr": "Innocent",
		"ru": "Искренний",
		"es": "Inocente",
		"es-419": "Inocente",
		"pt": "Puro",
		"ja": "純粋な",
		"ko": "순수한",
		"zh": "纯粹的",
		"zh-Hant": "純真的",
		"th": "ใสซื่อ",
		"tr": "Saf",
		"id": "Polos"
	},
	"Powerful": {
		"de": "Mächtig",
		"fr": "Puissant",
		"ru": "Стойкий",
		"es": "Poderoso",
		"es-419": "Resistente",
		"pt": "Osso Duro",
		"ja": "強靱な",
		"ko": "강인한",
		"zh": "坚韧的",
		"zh-Hant": "堅韌的",
		"th": "ทรงพลัง",
		"tr": "Güçlü",
		"id": "Tangguh"
	},
	"Quick": {
		"de": "Schnell",
		"fr": "Rapide",
		"ru": "Стремительный",
		"es": "Rápido",
		"es-419": "Rápido",
		"pt": "Ágil",
		"ja": "素早い",
		"ko": "재빠른",
		"zh": "敏捷的",
		"zh-Hant": "敏捷的",
		"th": "รวดเร็ว",
		"tr": "Hızlı",
		"id": "Cepat"
	},
	"Quick-Witted": {
		"de": "Schlagfertig",
		"fr": "Vif d'esprit",
		"ru": "Сообразительный",
		"es": "Espabilado",
		"es-419": "Astuto",
		"pt": "Rápido no Cálculo",
		"ja": "計算が速い",
		"ko": "계산이 빠른",
		"zh": "计算快的",
		"zh-Hant": "精於算計的",
		"th": "หัวไว",
		"tr": "Hesabı Kuvvetli",
		"id": "Pandai Menghitung"
	},
	"Realistic": {
		"de": "Sachlich",
		"fr": "Réaliste",
		"ru": "Приземленный",
		"es": "Realista",
		"es-419": "Realista",
		"pt": "Realista",
		"ja": "現実的な",
		"ko": "현실적인",
		"zh": "现实的",
		"zh-Hant": "現實的",
		"th": "อยู่กับความเป็นจริง",
		"tr": "Gerçekçi",
		"id": "Realistis"
	},
	"Smart": {
		"de": "Klug",
		"fr": "Intelligent",
		"ru": "Умный",
		"es": "Inteligente",
		"es-419": "Inteligente",
		"pt": "Inteligente",
		"ja": "頭のいい",
		"ko": "똑똑한",
		"zh": "聪明的",
		"zh-Hant": "聰明的",
		"th": "ฉลาด",
		"tr": "Akıllı",
		"id": "Pintar"
	},
	"Strong": {
		"de": "Stark",
		"fr": "Fort",
		"ru": "Сильный",
		"es": "Forzudo",
		"es-419": "Fuerte",
		"pt": "Forte",
		"ja": "力の強い",
		"ko": "힘이 센",
		"zh": "力气大的",
		"zh-Hant": "力氣大的",
		"th": "แข็งแรง",
		"tr": "Kuvvetli",
		"id": "Kuat"
	},
	"Tenacious": {
		"de": "Hartnäckig",
		"fr": "Tenace",
		"ru": "Настойчивый",
		"es": "Tenaz",
		"es-419": "Persistente",
		"pt": "Persistente",
		"ja": "粘り強い",
		"ko": "끈기가 있는",
		"zh": "有毅力的",
		"zh-Hant": "有毅力的",
		"th": "มีความอดทน",
		"tr": "Dirençli",
		"id": "Yang Gigih"
	},
	"Tough": {
		"de": "Zäh",
		"fr": "Coriace",
		"ru": "Крепкий",
		"es": "Duro",
		"es-419": "Rudo",
		"pt": "Resistente",
		"ja": "タフな",
		"ko": "터프한",
		"zh": "坚强的",
		"zh-Hant": "剛烈的",
		"th": "เข้มแข็ง",
		"tr": "Sağlam",
		"id": "Gagah"
	},
	"Treasure-Seeking": {
		"de": "Schatzsuchend",
		"fr": "En quête de trésor",
		"ru": "Искатель сокровищ",
		"es": "Buscatesoros",
		"es-419": "Buscando Tesoros",
		"pt": "Procurando o tesouro",
		"ja": "宝物を探す",
		"ko": "보물을 찾는",
		"zh": "寻宝中的",
		"zh-Hant": "尋寶的",
		"th": "หาสมบัติ",
		"tr": "Hazine Arayan",
		"id": "Pencari Harta Karun"
	}
};
