// Every sea crystal a ship can carry, and the Nols, read off BDOCodex
// on 2026-09-15 by tools/fetch-sea-crystals.mjs. One entry per
// codex id: a name is a grade, an id is one effect at one value.
//
// The grades, weakest first: Eltro, Serni, Zulatia, Margoria, Rusalka
// (2025-02-06, "slightly higher effects than Margoria" and, unlike the
// others, not limited to a sea area). Ebenruth's Nol shares the slot;
// the Oceanteared Nol (Rusalka Sea Crystal + Ebenruth's Nol, by
// Manufacture) carries both.

export const crystals = [
	{ id: 59321, name: "Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","and with BreezySail movement distance +50%"] },
	{ id: 59440, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Speed +4.5%"] },
	{ id: 59441, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Acceleration +4.5%"] },
	{ id: 59442, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Turn +9.0%"] },
	{ id: 59443, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Brake +9.0%"] },
	{ id: 59444, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Weight Limit +1,350 LT"] },
	{ id: 59445, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Max Durability +22,500"] },
	{ id: 59446, name: "Oceanteared Ebenruth's Nol", grade: 'nol', lt: 1, effects: ["After using BreezySail, use BreezySail 1 extra time","without consuming Stamina","Extra BreezySail movement distance +50%","Extra Damage to Ships and Sea Monsters +2340 x ship hits"] },
	{ id: 756501, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.1%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756502, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756503, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.3%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756504, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756505, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.5%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756506, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756507, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.7%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756508, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756509, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +0.9%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756510, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Movement Speed +1.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756511, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.1%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756512, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756513, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.3%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756514, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756515, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.5%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756516, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756517, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.7%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756518, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756519, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +1.9%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756520, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Movement Speed +2.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756521, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.1%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756522, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756523, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.3%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756524, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756525, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.5%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756526, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756527, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.7%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756528, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756529, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +2.9%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756530, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Movement Speed +3.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756531, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.1%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756532, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756533, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.3%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756534, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756535, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.5%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756536, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756537, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.7%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756538, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756539, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +3.9%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756540, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Movement Speed +4.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756541, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.1%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756542, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756543, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.3%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756544, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756545, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.5%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756546, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756547, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.7%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756548, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756549, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +0.9%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756550, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Acceleration +1.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756551, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.1%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756552, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756553, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.3%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756554, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756555, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.5%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756556, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756557, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.7%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756558, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756559, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +1.9%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756560, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Acceleration +2.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756561, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.1%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756562, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756563, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.3%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756564, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756565, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.5%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756566, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756567, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.7%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756568, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756569, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +2.9%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756570, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Acceleration +3.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756571, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.1%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756572, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756573, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.3%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756574, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756575, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.5%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756576, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756577, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.7%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756578, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756579, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +3.9%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756580, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Acceleration +4.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756581, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +0.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756582, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +0.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756583, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +0.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756584, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +0.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756585, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +1.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756586, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +1.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756587, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +1.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756588, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +1.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756589, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +1.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756590, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Turn +2.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756591, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +2.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756592, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +2.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756593, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +2.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756594, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +2.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756595, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +3.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756596, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +3.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756597, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +3.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756598, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +3.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756599, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +3.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756600, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Turn +4.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756601, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +4.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756602, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +4.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756603, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +4.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756604, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +4.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756605, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +5.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756606, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +5.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756607, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +5.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756608, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +5.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756609, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +5.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756610, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Turn +6.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756611, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +6.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756612, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +6.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756613, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +6.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756614, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +6.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756615, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +7.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756616, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +7.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756617, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +7.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756618, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +7.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756619, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +7.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756620, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Turn +8.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756621, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +0.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756622, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +0.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756623, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +0.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756624, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +0.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756625, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +1.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756626, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +1.2%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756627, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +1.4%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756628, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +1.6%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756629, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +1.8%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756630, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Brake +2.0%"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756631, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +2.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756632, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +2.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756633, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +2.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756634, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +2.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756635, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +3.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756636, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +3.2%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756637, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +3.4%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756638, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +3.6%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756639, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +3.8%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756640, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Brake +4.0%"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756641, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +4.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756642, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +4.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756643, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +4.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756644, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +4.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756645, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +5.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756646, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +5.2%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756647, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +5.4%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756648, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +5.6%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756649, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +5.8%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756650, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Brake +6.0%"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756651, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +6.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756652, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +6.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756653, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +6.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756654, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +6.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756655, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +7.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756656, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +7.2%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756657, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +7.4%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756658, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +7.6%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756659, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +7.8%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756660, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Brake +8.0%"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756661, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +30 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756662, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +60 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756663, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +90 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756664, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +120 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756665, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +150 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756666, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +180 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756667, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +210 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756668, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +240 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756669, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +270 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756670, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Weight Limit +300 LT"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756671, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +330 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756672, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +360 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756673, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +390 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756674, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +420 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756675, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +450 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756676, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +480 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756677, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +510 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756678, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +540 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756679, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +570 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756680, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Weight Limit +600 LT"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756681, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +630 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756682, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +660 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756683, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +690 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756684, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +720 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756685, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +750 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756686, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +780 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756687, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +810 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756688, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +840 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756689, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +870 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756690, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Weight Limit +900 LT"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756691, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +930 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756692, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +960 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756693, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +990 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756694, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,020 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756695, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,050 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756696, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,080 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756697, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,110 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756698, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,140 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756699, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,170 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756700, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Weight Limit +1,200 LT"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756701, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +500"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756702, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +1,000"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756703, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +1,500"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756704, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +2,000"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756705, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +2,500"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756706, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +3,000"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756707, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +3,500"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756708, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +4,000"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756709, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +4,500"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756710, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Max Durability +5,000"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756711, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +5,500"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756712, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +6,000"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756713, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +6,500"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756714, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +7,000"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756715, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +7,500"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756716, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +8,000"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756717, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +8,500"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756718, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +9,000"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756719, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +9,500"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756720, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Max Durability +10,000"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756721, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +10,500"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756722, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +11,000"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756723, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +11,500"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756724, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +12,000"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756725, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +12,500"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756726, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +13,000"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756727, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +13,500"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756728, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +14,000"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756729, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +14,500"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756730, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Max Durability +15,000"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756731, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +15,500"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756732, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +16,000"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756733, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +16,500"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756734, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +17,000"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756735, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +17,500"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756736, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +18,000"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756737, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +18,500"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756738, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +19,000"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756739, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +19,500"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756740, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Max Durability +20,000"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756741, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +52 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756742, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +104 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756743, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +156 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756744, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +208 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756745, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +260 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756746, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +312 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756747, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +364 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756748, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +416 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756749, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +468 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756750, name: "Eltro Sea Crystal", grade: 'eltro', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +520 x ship hits"], usage: "Install on big ships or craft Origin of Eltro" },
	{ id: 756751, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +572 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756752, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +624 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756753, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +676 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756754, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +728 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756755, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +780 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756756, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +832 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756757, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +884 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756758, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +936 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756759, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +988 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756760, name: "Serni Sea Crystal", grade: 'serni', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1040 x ship hits"], usage: "Install on big ships or craft Origin of Serni" },
	{ id: 756761, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1092 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756762, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1144 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756763, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1196 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756764, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1248 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756765, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1300 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756766, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1352 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756767, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1404 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756768, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1456 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756769, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1508 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756770, name: "Zulatia Sea Crystal", grade: 'zulatia', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1560 x ship hits"], usage: "Install on big ships or craft Origin of Zulatia" },
	{ id: 756771, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1612 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756772, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1664 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756773, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1716 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756774, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships, Extra Damage to Sea Monsters +1768 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756775, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1820 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756776, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1872 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756777, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1924 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756778, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +1976 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756779, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +2028 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756780, name: "Margoria Sea Crystal", grade: 'margoria', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +2080 x ship hits"], usage: "Install on big ships or craft Origin of Margoria" },
	{ id: 756821, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Speed +4.5%"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756822, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Acceleration +4.5%"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756823, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Turn +9.0%"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756824, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Brake +9.0%"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756825, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Weight Limit +1,350 LT"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756826, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Max Durability +22,500"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" },
	{ id: 756827, name: "Rusalka Sea Crystal", grade: 'rusalka', lt: 1, effects: ["Extra Damage to Ships and Sea Monsters +2340 x ship hits"], usage: "Install on big ships or craft Origin of Rusalka/Oceanteared Ebenruth&#39;s Nol" }
];

export const crystalById = Object.fromEntries(crystals.map(c => [c.id, c]));
