// Crow coin costs for items

export const coins = {
    "Khan's Concentrated Magic": 80000,
    "Luminous Cobalt Ingot": 500,
    "Bright Reef Piece": 40,
    "Great Ocean Dark Iron": 160,
    "Cobalt Ingot": 150,
    "Brilliant Rock Salt Ingot": 500,
    "Seaweed Stalk": 100,
    "Enhanced Island Tree Coated Plywood": 50,
    "Pure Pearl Crystal": 250,
    "Cox Pirates' Artifact (Parley Beginner)": 150,
    "Cox Pirates' Artifact (Parley Expert)": 500,
    "Cox Pirates' Artifact (Combat)": 150,
    "Deep Sea Memory Filled Glue": 140,
    "Brilliant Pearl Shard": 500,
    "Ruddy Manganese Nodule": 250,
    "Tear of the Ocean": 500,
    "Khan's Tendon": 500,
    "Khan's Scale": 200,
    "Tidal Black Stone": 10,
    "Tide-Dyed Standardized Timber Square": 100,
    "Deep Tide-Dyed Standardized Timber Square": 100,
    "Moon Vein Flax Fabric": 50,
    "Moon Scale Plywood": 20,
    "Mandragora Essence": 100,
    "Glue With Traces of Deep Waves": 500,
    "Crow Coin Coupon": 10,
    "Delicately Polished Support": 350,
    "Ebenruth's Nol": 2000000,
    "Epheria Carrack: Toro Cannon": 10000,
    "Epheria Carrack: Toro Figurehead": 10000,
    "Epheria Carrack: Toro Plating": 10000,
    "Epheria Carrack: Toro Sail": 10000,
    "Fountain of Divine Melodies": 10000,
    "Hero's Small Lamp": 100,
    "Oquilla Aquamarine Fresh Water": 20,
    "Oquilla Crimson Fresh Water": 40,
    "Oquilla Emerald Fresh Water": 10,
    "Oquilla Golden Fresh Water": 30,
    "Oquilla's Flower": 1000,
    "Oquilla's Tear": 100000,
    "Panokseon: Haemo's Cannon": 10000,
    "Panokseon: Haemo's Figurehead": 10000,
    "Panokseon: Haemo's Plating": 10000,
    "Panokseon: Haemo's Sail": 10000,
    "Ravinia's Moss Remover": 100,
    "Sealed Compass (7 Days)": 400,
    "Starlight Emulsifier": 250,
    "Starlight Hardener": 250,
    "Tidal Blue Lamp Post": 500,
    "Violent Wave Plywood": 350,
    "Void Sea Crystal": 10,
    "Wave Residue Adhesive": 350
};