// Crow Coin costs, as shown in the Crow Coin Shop at Oquilla's Eye.
//
// Checked against the in-game shop on 2026-08-25. Most sailing materials
// came down by roughly 20% at some point before that; anything not listed
// on the shop pages read that day is left at its previous value.

export const coins = {
    "Khan's Concentrated Magic": 80000,
    "Luminous Cobalt Ingot": 400,
    "Bright Reef Piece": 30,
    "Great Ocean Dark Iron": 130,
    "Cobalt Ingot": 120,
    "Brilliant Rock Salt Ingot": 400,
    "Seaweed Stalk": 80,
    "Enhanced Island Tree Coated Plywood": 40,
    "Pure Pearl Crystal": 200,
    "Cox Pirates' Artifact (Parley Beginner)": 120,
    "Cox Pirates' Artifact (Parley Expert)": 400,
    "Cox Pirates' Artifact (Combat)": 120,
    "Deep Sea Memory Filled Glue": 110,
    "Brilliant Pearl Shard": 400,
    "Ruddy Manganese Nodule": 200,
    "Tear of the Ocean": 400,
    "Khan's Tendon": 400,
    "Khan's Scale": 160,
    "Tidal Black Stone": 10,
    "Tide-Dyed Standardized Timber Square": 80,
    "Deep Tide-Dyed Standardized Timber Square": 80,
    "Moon Vein Flax Fabric": 40,
    "Moon Scale Plywood": 15,
    "Mandragora Essence": 100,
    "Glue With Traces of Deep Waves": 400,
    "Crow Coin Coupon": 10,
    "Delicately Polished Support": 300,
    "Ebenruth's Nol": 2000000,
    "Epheria Carrack: Toro Cannon": 10000,
    "Epheria Carrack: Toro Figurehead": 10000,
    "Epheria Carrack: Toro Plating": 10000,
    "Epheria Carrack: Toro Sail": 10000,
    "Fountain of Divine Melodies": 10000,
    "Hero's Small Lamp": 100,
    "Oquilla Aquamarine Fresh Water": 20,
    "Oquilla Crimson Fresh Water": 40,
    "Oquilla Emerald Fresh Water": 10,
    "Oquilla Golden Fresh Water": 30,
    "Oquilla's Flower": 1000,
    "Oquilla's Tear": 100000,
    "Panokseon: Haemo's Cannon": 10000,
    "Panokseon: Haemo's Figurehead": 10000,
    "Panokseon: Haemo's Plating": 10000,
    "Panokseon: Haemo's Sail": 10000,
    "Ravinia's Moss Remover": 100,
    "Sealed Compass (7 Days)": 400,
    "Starlight Emulsifier": 200,
    "Starlight Hardener": 200,
    "Tidal Blue Lamp Post": 500,
    "Violent Wave Plywood": 300,
    "Void Sea Crystal": 10,
    "Wave Residue Adhesive": 300
};
