// List of supported trackable targets (ships and craftable ship parts)

import { TT } from './i18n.js';

export const shipGroups = [
	{
		name: "Ships",
		items: [
			"Epheria Sailboat",
			"Improved Epheria Sailboat",
			"Epheria Caravel",
			"Carrack (Advance)",
			"Carrack (Balance)",
			"Epheria Frigate",
			"Improved Epheria Frigate",
			"Epheria Galleass",
			"Carrack (Volante)",
			"Carrack (Valor)",
			"Panokseon",
		]
	},
	{
		name: "Small craft",
		items: [
			"Epheria Cog",
			"Rowboat",
			"Calpheon Rowboat",
			"Mediah Rowboat",
			"Raft",
		]
	},
	{
		name: "Carrack Parts (Chiro)",
		items: [
			"Epheria Carrack: Advance (Chiro's Cannon)",
			"Epheria Carrack: Advance (Chiro's Sail)",
			"Epheria Carrack: Advance (Chiro's Figurehead)",
			"Epheria Carrack: Advance (Chiro's Black Plating)",
			"Epheria Carrack: Balance (Chiro's Cannon)",
			"Epheria Carrack: Balance (Chiro's Sail)",
			"Epheria Carrack: Balance (Chiro's Figurehead)",
			"Epheria Carrack: Balance (Chiro's Black Plating)",
			"Epheria Carrack: Volante (Chiro's Cannon)",
			"Epheria Carrack: Volante (Chiro's Sail)",
			"Epheria Carrack: Volante (Chiro's Figurehead)",
			"Epheria Carrack: Volante (Chiro's Black Plating)",
			"Epheria Carrack: Valor (Chiro's Cannon)",
			"Epheria Carrack: Valor (Chiro's Sail)",
			"Epheria Carrack: Valor (Chiro's Figurehead)",
			"Epheria Carrack: Valor (Chiro's Black Plating)",
		]
	},
	{
		name: "Panokseon Parts (Byukgye)",
		items: [
			"Panokseon: Byukgye's Enhanced Cannon",
			"Panokseon: Byukgye's Enhanced Sail",
			"Panokseon: Byukgye's Enhanced Figurehead",
			"Panokseon: Byukgye's Enhanced Plating",
		]
	},
	{
		name: "Carrack Parts (Falasi, yellow)",
		items: [
			"Epheria Carrack: Advance (Falasi's Cannon)",
			"Epheria Carrack: Advance (Falasi's Sail)",
			"Epheria Carrack: Advance (Falasi's Figurehead)",
			"Epheria Carrack: Advance (Falasi's Plating)",
			"Epheria Carrack: Balance (Falasi's Cannon)",
			"Epheria Carrack: Balance (Falasi's Sail)",
			"Epheria Carrack: Balance (Falasi's Figurehead)",
			"Epheria Carrack: Balance (Falasi's Plating)",
			"Epheria Carrack: Volante (Falasi's Cannon)",
			"Epheria Carrack: Volante (Falasi's Sail)",
			"Epheria Carrack: Volante (Falasi's Figurehead)",
			"Epheria Carrack: Volante (Falasi's Plating)",
			"Epheria Carrack: Valor (Falasi's Cannon)",
			"Epheria Carrack: Valor (Falasi's Sail)",
			"Epheria Carrack: Valor (Falasi's Figurehead)",
			"Epheria Carrack: Valor (Falasi's Plating)",
		]
	},
	{
		name: "Panokseon Parts (Cheongun, yellow)",
		items: [
			"Panokseon: Cheongun's Enhanced Cannon",
			"Panokseon: Cheongun's Enhanced Sail",
			"Panokseon: Cheongun's Enhanced Figurehead",
			"Panokseon: Cheongun's Enhanced Plating",
		]
	},
];

export const ships = shipGroups.flatMap(g => g.items);

export const shipDescriptions = {
	"Epheria Sailboat": TT("Entry-level ocean vessel for exploration"),
	"Improved Epheria Sailboat": TT("Enhanced sailboat with better performance"),
	"Epheria Caravel": TT("Versatile trading vessel with cargo capacity"),
	"Carrack (Advance)": TT("High-speed carrack for fast travel"),
	"Carrack (Balance)": TT("Well-rounded carrack for all activities"),
	"Epheria Frigate": TT("Combat vessel for sea monster hunting"),
	"Improved Epheria Frigate": TT("Enhanced frigate with superior firepower"),
	"Epheria Galleass": TT("Large cargo ship for extensive trading"),
	"Carrack (Volante)": TT("Speed-focused carrack for rapid traversal"),
	"Carrack (Valor)": TT("Combat-oriented carrack with firepower"),
	"Panokseon": TT("Traditional Korean warship"),
	"Epheria Cog": TT("A fast, fragile runabout with no sailors, no cannons and a lifespan repairs cannot restore"),
	"Rowboat": TT("The coastal boat for the first Great Ocean errands"),
	"Calpheon Rowboat": TT("A Rowboat with a little more weight allowance"),
	"Mediah Rowboat": TT("A Rowboat built from Mediah's materials"),
	"Raft": TT("Twenty-five logs and some powder"),
	"Epheria Carrack: Advance (Chiro's Cannon)": TT("Blue cannon for Carrack (Advance) - crafted from a +10 Toro cannon at Iliya Island"),
	"Epheria Carrack: Advance (Chiro's Sail)": TT("Blue sail for Carrack (Advance) - crafted from a +10 Toro sail at Iliya Island"),
	"Epheria Carrack: Advance (Chiro's Figurehead)": TT("Blue figurehead for Carrack (Advance) - crafted from a +10 Toro figurehead at Iliya Island"),
	"Epheria Carrack: Advance (Chiro's Black Plating)": TT("Blue black plating for Carrack (Advance) - crafted from a +10 Toro black plating at Iliya Island"),
	"Epheria Carrack: Balance (Chiro's Cannon)": TT("Blue cannon for Carrack (Balance) - crafted from a +10 Toro cannon at Iliya Island"),
	"Epheria Carrack: Balance (Chiro's Sail)": TT("Blue sail for Carrack (Balance) - crafted from a +10 Toro sail at Iliya Island"),
	"Epheria Carrack: Balance (Chiro's Figurehead)": TT("Blue figurehead for Carrack (Balance) - crafted from a +10 Toro figurehead at Iliya Island"),
	"Epheria Carrack: Balance (Chiro's Black Plating)": TT("Blue black plating for Carrack (Balance) - crafted from a +10 Toro black plating at Iliya Island"),
	"Epheria Carrack: Volante (Chiro's Cannon)": TT("Blue cannon for Carrack (Volante) - crafted from a +10 Toro cannon at Iliya Island"),
	"Epheria Carrack: Volante (Chiro's Sail)": TT("Blue sail for Carrack (Volante) - crafted from a +10 Toro sail at Iliya Island"),
	"Epheria Carrack: Volante (Chiro's Figurehead)": TT("Blue figurehead for Carrack (Volante) - crafted from a +10 Toro figurehead at Iliya Island"),
	"Epheria Carrack: Volante (Chiro's Black Plating)": TT("Blue black plating for Carrack (Volante) - crafted from a +10 Toro black plating at Iliya Island"),
	"Epheria Carrack: Valor (Chiro's Cannon)": TT("Blue cannon for Carrack (Valor) - crafted from a +10 Toro cannon at Iliya Island"),
	"Epheria Carrack: Valor (Chiro's Sail)": TT("Blue sail for Carrack (Valor) - crafted from a +10 Toro sail at Iliya Island"),
	"Epheria Carrack: Valor (Chiro's Figurehead)": TT("Blue figurehead for Carrack (Valor) - crafted from a +10 Toro figurehead at Iliya Island"),
	"Epheria Carrack: Valor (Chiro's Black Plating)": TT("Blue black plating for Carrack (Valor) - crafted from a +10 Toro black plating at Iliya Island"),
	"Epheria Carrack: Advance (Falasi's Cannon)": TT("Yellow cannon for Carrack (Advance) - crafted from a +10 Chiro cannon at Iliya Island"),
	"Epheria Carrack: Advance (Falasi's Sail)": TT("Yellow sail for Carrack (Advance) - crafted from a +10 Chiro sail at Iliya Island"),
	"Epheria Carrack: Advance (Falasi's Figurehead)": TT("Yellow figurehead for Carrack (Advance) - crafted from a +10 Chiro figurehead at Iliya Island"),
	"Epheria Carrack: Advance (Falasi's Plating)": TT("Yellow plating for Carrack (Advance) - crafted from a +10 Chiro black plating at Iliya Island"),
	"Epheria Carrack: Balance (Falasi's Cannon)": TT("Yellow cannon for Carrack (Balance) - crafted from a +10 Chiro cannon at Iliya Island"),
	"Epheria Carrack: Balance (Falasi's Sail)": TT("Yellow sail for Carrack (Balance) - crafted from a +10 Chiro sail at Iliya Island"),
	"Epheria Carrack: Balance (Falasi's Figurehead)": TT("Yellow figurehead for Carrack (Balance) - crafted from a +10 Chiro figurehead at Iliya Island"),
	"Epheria Carrack: Balance (Falasi's Plating)": TT("Yellow plating for Carrack (Balance) - crafted from a +10 Chiro black plating at Iliya Island"),
	"Epheria Carrack: Volante (Falasi's Cannon)": TT("Yellow cannon for Carrack (Volante) - crafted from a +10 Chiro cannon at Iliya Island"),
	"Epheria Carrack: Volante (Falasi's Sail)": TT("Yellow sail for Carrack (Volante) - crafted from a +10 Chiro sail at Iliya Island"),
	"Epheria Carrack: Volante (Falasi's Figurehead)": TT("Yellow figurehead for Carrack (Volante) - crafted from a +10 Chiro figurehead at Iliya Island"),
	"Epheria Carrack: Volante (Falasi's Plating)": TT("Yellow plating for Carrack (Volante) - crafted from a +10 Chiro black plating at Iliya Island"),
	"Epheria Carrack: Valor (Falasi's Cannon)": TT("Yellow cannon for Carrack (Valor) - crafted from a +10 Chiro cannon at Iliya Island"),
	"Epheria Carrack: Valor (Falasi's Sail)": TT("Yellow sail for Carrack (Valor) - crafted from a +10 Chiro sail at Iliya Island"),
	"Epheria Carrack: Valor (Falasi's Figurehead)": TT("Yellow figurehead for Carrack (Valor) - crafted from a +10 Chiro figurehead at Iliya Island"),
	"Epheria Carrack: Valor (Falasi's Plating)": TT("Yellow plating for Carrack (Valor) - crafted from a +10 Chiro black plating at Iliya Island"),
	"Panokseon: Byukgye's Enhanced Cannon": TT("Blue cannon for the Panokseon - crafted from a +10 Haemo's cannon at Cheongsa Island"),
	"Panokseon: Byukgye's Enhanced Sail": TT("Blue sail for the Panokseon - crafted from a +10 Haemo's sail at Cheongsa Island"),
	"Panokseon: Byukgye's Enhanced Figurehead": TT("Blue figurehead for the Panokseon - crafted from a +10 Haemo's figurehead at Cheongsa Island"),
	"Panokseon: Byukgye's Enhanced Plating": TT("Blue plating for the Panokseon - crafted from a +10 Haemo's plating at Cheongsa Island"),
	"Panokseon: Cheongun's Enhanced Cannon": TT("Yellow cannon for the Panokseon - crafted from a +10 Byukgye's cannon at Cheongsa Island"),
	"Panokseon: Cheongun's Enhanced Sail": TT("Yellow sail for the Panokseon - crafted from a +10 Byukgye's sail at Cheongsa Island"),
	"Panokseon: Cheongun's Enhanced Figurehead": TT("Yellow figurehead for the Panokseon - crafted from a +10 Byukgye's figurehead at Cheongsa Island"),
	"Panokseon: Cheongun's Enhanced Plating": TT("Yellow plating for the Panokseon - crafted from a +10 Byukgye's plating at Cheongsa Island"),
};
