// Total sub-materials count for each ship
// Auto-generated by calculate_totals.js

export const shipMaterialTotals = {
	"Epheria Sailboat": 1411,
	"Improved Epheria Sailboat": 1095,
	"Epheria Caravel": 60514,
	"Carrack (Advance)": 2231,
	"Carrack (Balance)": 2229,
	"Epheria Frigate": 1761,
	"Improved Epheria Frigate": 1095,
	"Epheria Galleass": 60421,
	"Carrack (Volante)": 2636,
	"Carrack (Valor)": 2632,
	"Panokseon": 3480
};