// Craft system index and statistics
// Auto-generated on: 2025-08-21T19:23:56.800Z

export const data = {
    "ships": [
        "Epheria Sailboat",
        "Improved Epheria Sailboat",
        "Epheria Caravel",
        "Carrack (Advance)",
        "Carrack (Balance)",
        "Epheria Frigate",
        "Improved Epheria Frigate",
        "Epheria Galleass",
        "Carrack (Volante)",
        "Carrack (Valor)",
        "Panokseon"
    ],
    "ship_parts": [
        "Epheria Caravel: Black Dragon Figurehead",
        "Epheria Caravel: Upgraded Plating",
        "Epheria Caravel: Mayna Cannon",
        "Epheria Caravel: Stratus Wind Sail",
        "Epheria Galleass: Black Dragon Figurehead",
        "Epheria Galleass: Upgraded Plating",
        "Epheria Galleass: Mayna Cannon",
        "Epheria Galleass: Stratus Wind Sail",
        "+10 Bartali Sailboat: Old Figurehead",
        "+9 Bartali Sailboat: Old Figurehead",
        "+8 Bartali Sailboat: Old Figurehead",
        "+7 Bartali Sailboat: Old Figurehead",
        "+6 Bartali Sailboat: Old Figurehead",
        "+5 Bartali Sailboat: Old Figurehead",
        "+4 Bartali Sailboat: Old Figurehead",
        "+3 Bartali Sailboat: Old Figurehead",
        "+2 Bartali Sailboat: Old Figurehead",
        "+1 Bartali Sailboat: Old Figurehead",
        "+10 Bartali Sailboat: Old Plating",
        "+9 Bartali Sailboat: Old Plating",
        "+8 Bartali Sailboat: Old Plating",
        "+7 Bartali Sailboat: Old Plating",
        "+6 Bartali Sailboat: Old Plating",
        "+5 Bartali Sailboat: Old Plating",
        "+4 Bartali Sailboat: Old Plating",
        "+3 Bartali Sailboat: Old Plating",
        "+2 Bartali Sailboat: Old Plating",
        "+1 Bartali Sailboat: Old Plating",
        "+10 Bartali Sailboat: Old Cannon",
        "+9 Bartali Sailboat: Old Cannon",
        "+8 Bartali Sailboat: Old Cannon",
        "+7 Bartali Sailboat: Old Cannon",
        "+6 Bartali Sailboat: Old Cannon",
        "+5 Bartali Sailboat: Old Cannon",
        "+4 Bartali Sailboat: Old Cannon",
        "+3 Bartali Sailboat: Old Cannon",
        "+2 Bartali Sailboat: Old Cannon",
        "+1 Bartali Sailboat: Old Cannon",
        "+10 Bartali Sailboat: Old Wind Sail",
        "+9 Bartali Sailboat: Old Wind Sail",
        "+8 Bartali Sailboat: Old Wind Sail",
        "+7 Bartali Sailboat: Old Wind Sail",
        "+6 Bartali Sailboat: Old Wind Sail",
        "+5 Bartali Sailboat: Old Wind Sail",
        "+4 Bartali Sailboat: Old Wind Sail",
        "+3 Bartali Sailboat: Old Wind Sail",
        "+2 Bartali Sailboat: Old Wind Sail",
        "+1 Bartali Sailboat: Old Wind Sail",
        "+10 Epheria: Old Figurehead",
        "+9 Epheria: Old Figurehead",
        "+8 Epheria: Old Figurehead",
        "+7 Epheria: Old Figurehead",
        "+6 Epheria: Old Figurehead",
        "+5 Epheria: Old Figurehead",
        "+4 Epheria: Old Figurehead",
        "+3 Epheria: Old Figurehead",
        "+2 Epheria: Old Figurehead",
        "+1 Epheria: Old Figurehead",
        "+10 Epheria: Old Plating",
        "+9 Epheria: Old Plating",
        "+8 Epheria: Old Plating",
        "+7 Epheria: Old Plating",
        "+6 Epheria: Old Plating",
        "+5 Epheria: Old Plating",
        "+4 Epheria: Old Plating",
        "+3 Epheria: Old Plating",
        "+2 Epheria: Old Plating",
        "+1 Epheria: Old Plating",
        "+10 Epheria: Old Cannon",
        "+9 Epheria: Old Cannon",
        "+8 Epheria: Old Cannon",
        "+7 Epheria: Old Cannon",
        "+6 Epheria: Old Cannon",
        "+5 Epheria: Old Cannon",
        "+4 Epheria: Old Cannon",
        "+3 Epheria: Old Cannon",
        "+2 Epheria: Old Cannon",
        "+1 Epheria: Old Cannon",
        "+10 Epheria: Old Wind Sail",
        "+9 Epheria: Old Wind Sail",
        "+8 Epheria: Old Wind Sail",
        "+7 Epheria: Old Wind Sail",
        "+6 Epheria: Old Wind Sail",
        "+5 Epheria: Old Wind Sail",
        "+4 Epheria: Old Wind Sail",
        "+3 Epheria: Old Wind Sail",
        "+2 Epheria: Old Wind Sail",
        "+1 Epheria: Old Wind Sail",
        "+10 Epheria Caravel: Brass Figurehead",
        "+9 Epheria Caravel: Brass Figurehead",
        "+8 Epheria Caravel: Brass Figurehead",
        "+7 Epheria Caravel: Brass Figurehead",
        "+6 Epheria Caravel: Brass Figurehead",
        "+5 Epheria Caravel: Brass Figurehead",
        "+4 Epheria Caravel: Brass Figurehead",
        "+3 Epheria Caravel: Brass Figurehead",
        "+2 Epheria Caravel: Brass Figurehead",
        "+1 Epheria Caravel: Brass Figurehead",
        "+10 Epheria Caravel: Upgraded Plating",
        "+9 Epheria Caravel: Upgraded Plating",
        "+8 Epheria Caravel: Upgraded Plating",
        "+7 Epheria Caravel: Upgraded Plating",
        "+6 Epheria Caravel: Upgraded Plating",
        "+5 Epheria Caravel: Upgraded Plating",
        "+4 Epheria Caravel: Upgraded Plating",
        "+3 Epheria Caravel: Upgraded Plating",
        "+2 Epheria Caravel: Upgraded Plating",
        "+1 Epheria Caravel: Upgraded Plating",
        "+10 Epheria Caravel: Verisha Cannon",
        "+9 Epheria Caravel: Verisha Cannon",
        "+8 Epheria Caravel: Verisha Cannon",
        "+7 Epheria Caravel: Verisha Cannon",
        "+6 Epheria Caravel: Verisha Cannon",
        "+5 Epheria Caravel: Verisha Cannon",
        "+4 Epheria Caravel: Verisha Cannon",
        "+3 Epheria Caravel: Verisha Cannon",
        "+2 Epheria Caravel: Verisha Cannon",
        "+1 Epheria Caravel: Verisha Cannon",
        "+10 Epheria Caravel: White Wind Sail",
        "+9 Epheria Caravel: White Wind Sail",
        "+8 Epheria Caravel: White Wind Sail",
        "+7 Epheria Caravel: White Wind Sail",
        "+6 Epheria Caravel: White Wind Sail",
        "+5 Epheria Caravel: White Wind Sail",
        "+4 Epheria Caravel: White Wind Sail",
        "+3 Epheria Caravel: White Wind Sail",
        "+2 Epheria Caravel: White Wind Sail",
        "+1 Epheria Caravel: White Wind Sail",
        "+10 Epheria Galleass: White Horn Figurehead",
        "+9 Epheria Galleass: White Horn Figurehead",
        "+8 Epheria Galleass: White Horn Figurehead",
        "+7 Epheria Galleass: White Horn Figurehead",
        "+6 Epheria Galleass: White Horn Figurehead",
        "+5 Epheria Galleass: White Horn Figurehead",
        "+4 Epheria Galleass: White Horn Figurehead",
        "+3 Epheria Galleass: White Horn Figurehead",
        "+2 Epheria Galleass: White Horn Figurehead",
        "+1 Epheria Galleass: White Horn Figurehead",
        "+10 Epheria Galleass: Upgraded Plating",
        "+9 Epheria Galleass: Upgraded Plating",
        "+8 Epheria Galleass: Upgraded Plating",
        "+7 Epheria Galleass: Upgraded Plating",
        "+6 Epheria Galleass: Upgraded Plating",
        "+5 Epheria Galleass: Upgraded Plating",
        "+4 Epheria Galleass: Upgraded Plating",
        "+3 Epheria Galleass: Upgraded Plating",
        "+2 Epheria Galleass: Upgraded Plating",
        "+1 Epheria Galleass: Upgraded Plating",
        "+10 Epheria Galleass: Verisha Cannon",
        "+9 Epheria Galleass: Verisha Cannon",
        "+8 Epheria Galleass: Verisha Cannon",
        "+7 Epheria Galleass: Verisha Cannon",
        "+6 Epheria Galleass: Verisha Cannon",
        "+5 Epheria Galleass: Verisha Cannon",
        "+4 Epheria Galleass: Verisha Cannon",
        "+3 Epheria Galleass: Verisha Cannon",
        "+2 Epheria Galleass: Verisha Cannon",
        "+1 Epheria Galleass: Verisha Cannon",
        "+10 Epheria Galleass: White Wind Sail",
        "+9 Epheria Galleass: White Wind Sail",
        "+8 Epheria Galleass: White Wind Sail",
        "+7 Epheria Galleass: White Wind Sail",
        "+6 Epheria Galleass: White Wind Sail",
        "+5 Epheria Galleass: White Wind Sail",
        "+4 Epheria Galleass: White Wind Sail",
        "+3 Epheria Galleass: White Wind Sail",
        "+2 Epheria Galleass: White Wind Sail",
        "+1 Epheria Galleass: White Wind Sail",
        "+10 Epheria Caravel: Black Dragon Figurehead",
        "+9 Epheria Caravel: Black Dragon Figurehead",
        "+8 Epheria Caravel: Black Dragon Figurehead",
        "+7 Epheria Caravel: Black Dragon Figurehead",
        "+6 Epheria Caravel: Black Dragon Figurehead",
        "+5 Epheria Caravel: Black Dragon Figurehead",
        "+4 Epheria Caravel: Black Dragon Figurehead",
        "+3 Epheria Caravel: Black Dragon Figurehead",
        "+2 Epheria Caravel: Black Dragon Figurehead",
        "+1 Epheria Caravel: Black Dragon Figurehead",
        "+10 Epheria Caravel: Mayna Cannon",
        "+9 Epheria Caravel: Mayna Cannon",
        "+8 Epheria Caravel: Mayna Cannon",
        "+7 Epheria Caravel: Mayna Cannon",
        "+6 Epheria Caravel: Mayna Cannon",
        "+5 Epheria Caravel: Mayna Cannon",
        "+4 Epheria Caravel: Mayna Cannon",
        "+3 Epheria Caravel: Mayna Cannon",
        "+2 Epheria Caravel: Mayna Cannon",
        "+1 Epheria Caravel: Mayna Cannon",
        "+10 Epheria Caravel: Stratus Wind Sail",
        "+9 Epheria Caravel: Stratus Wind Sail",
        "+8 Epheria Caravel: Stratus Wind Sail",
        "+7 Epheria Caravel: Stratus Wind Sail",
        "+6 Epheria Caravel: Stratus Wind Sail",
        "+5 Epheria Caravel: Stratus Wind Sail",
        "+4 Epheria Caravel: Stratus Wind Sail",
        "+3 Epheria Caravel: Stratus Wind Sail",
        "+2 Epheria Caravel: Stratus Wind Sail",
        "+1 Epheria Caravel: Stratus Wind Sail",
        "+10 Epheria Galleass: Black Dragon Figurehead",
        "+9 Epheria Galleass: Black Dragon Figurehead",
        "+8 Epheria Galleass: Black Dragon Figurehead",
        "+7 Epheria Galleass: Black Dragon Figurehead",
        "+6 Epheria Galleass: Black Dragon Figurehead",
        "+5 Epheria Galleass: Black Dragon Figurehead",
        "+4 Epheria Galleass: Black Dragon Figurehead",
        "+3 Epheria Galleass: Black Dragon Figurehead",
        "+2 Epheria Galleass: Black Dragon Figurehead",
        "+1 Epheria Galleass: Black Dragon Figurehead",
        "+10 Epheria Galleass: Mayna Cannon",
        "+9 Epheria Galleass: Mayna Cannon",
        "+8 Epheria Galleass: Mayna Cannon",
        "+7 Epheria Galleass: Mayna Cannon",
        "+6 Epheria Galleass: Mayna Cannon",
        "+5 Epheria Galleass: Mayna Cannon",
        "+4 Epheria Galleass: Mayna Cannon",
        "+3 Epheria Galleass: Mayna Cannon",
        "+2 Epheria Galleass: Mayna Cannon",
        "+1 Epheria Galleass: Mayna Cannon",
        "+10 Epheria Galleass: Stratus Wind Sail",
        "+9 Epheria Galleass: Stratus Wind Sail",
        "+8 Epheria Galleass: Stratus Wind Sail",
        "+7 Epheria Galleass: Stratus Wind Sail",
        "+6 Epheria Galleass: Stratus Wind Sail",
        "+5 Epheria Galleass: Stratus Wind Sail",
        "+4 Epheria Galleass: Stratus Wind Sail",
        "+3 Epheria Galleass: Stratus Wind Sail",
        "+2 Epheria Galleass: Stratus Wind Sail",
        "+1 Epheria Galleass: Stratus Wind Sail"
    ],
    "materials": [
        "Finely Polished Pine Plywood",
        "Graphite Ingot for Upgrade",
        "Timber for Upgrade",
        "Adhesive for Upgrade"
    ],
    "stats": {
        "totalShips": 11,
        "totalShipParts": 228,
        "totalMaterials": 4,
        "totalCrafts": 243
    },
    "generated": "2025-08-21T19:23:56.800Z"
};
